### ISSUE TITLE
Custom utctime postgresql type

### ISSUE THREAD

**Issue by andr3w321** [BurntSushi/nfldb#101]
Perhaps someone can help me out with this.  I'm trying to create some custom tables and used the custom type `utctime` but I'm having trouble inserting data into this field.

sql code
```
DROP TABLE IF EXISTS test;
CREATE TABLE test(updated_at utctime);
INSERT INTO test(updated_at) VALUES('2015-09-17 04:10:04.960339+00:00');
ERROR:  value for domain utctime violates check constraint "utctime_check"
```
The timestamp I am grabbing is from https://github.com/BurntSushi/nfldb/blob/master/nfldb/db.py#L191 `datetime.datetime.now(pytz.utc)`

The sql code for the constraint is found in nfldb.sql and is as follows
```
CREATE DOMAIN utctime AS timestamp with time zone
	CONSTRAINT utctime_check CHECK ((date_part('timezone'::text, VALUE) = (0)::double precision));
```

**Comment by andr3w321** [comment]
Ah finally figured it out.  Have to `SET TIME ZONE 'UTC';` before inserting.

**Comment by BurntSushi** [comment]
Glad you got it figured out. I <3 constraints: they prevent so many bugs!
