### ISSUE TITLE
Justin Tucker has only 7 PAT according to NFLDB, but 9 in reality

### ISSUE THREAD

**Issue by lark047** [BurntSushi/nfldb#106]
I'm just starting to get familiar with the query functionality, so I may have done something wrong, but in trying to calculate points for my fantasy team, I saw that Justin Tucker has only 7 PATs according to NFLDB. NFL.com has 9 PATs, though.

![jt](https://cloud.githubusercontent.com/assets/6484500/10254052/4f4bcd9c-690f-11e5-951b-6a41d58f8d42.PNG)

Here's my script:

```python
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)
points = 0

q.player(full_name = 'Justin Tucker')
q.game(season_type = 'Regular', season_year = 2015)

for st in q.as_aggregate():
  print '%d PATs (%d)' % (st.kicking_xpmade, st.kicking_xpmade * 1)
  points += st.kicking_xpmade * 1

print 'Justin Tucker scored %d points in 2015 so far' % points
```

output:

```
7 PATs (7)
Justin Tucker scored 7 points in 2015 so far
```

**Comment by andr3w321** [comment]
It seems to be missing one from the game 1 vs DEN and one from game 3 vs CIN
http://espn.go.com/nfl/player/_/id/15683/justin-tucker

```
nfldb=> select gsis_id,kicking_xpmade from play_player where player_id = '00-0029597' and kicking_xpa = 1 and gsis_id > '2015091200';
  gsis_id   | kicking_xpmade 
------------+----------------
 2015092010 |              1
 2015092010 |              1
 2015092010 |              1
 2015092707 |              1
 2015092707 |              1
 2015100100 |              1
 2015100100 |              1
```

**Comment by lark047** [comment]
Yeah, it seems that the PATs that are missing resulted from defensive scores.

**Comment by BurntSushi** [comment]
XP's are often left out of the GameCenter JSON data, and therefore are never added to nfldb.

In order for this to be a bug, you'll have to dig into the source JSON data for the games and show that there are XP's there that aren't in nfldb. Looking at total statistics over the season from NFL.com isn't necessarily derived from the same data feed.

**Comment by andr3w321** [comment]
It's missing from the GameCenter JSON data.  http://www.nfl.com/gamecenter/2015092707/2015/REG3/bengals@ravens#menu=gameinfo|contentId%3A0ap3000000541648&tab=analyze&recap=fullstory&analyze=playbyplay  Check out 4th Quarter, Cincinnati Bengals at 09:04.  The drive ends with a TD not XP.

**Comment by lark047** [comment]
I'll see if I can contact the GC devs then. Thanks for taking a look.
