### ISSUE TITLE
London Games don't have correct start time

### ISSUE THREAD

**Issue by joshutt** [BurntSushi/nfldb#107]
Today's London game doesn't have the correct start time in the game table.  In my database it is showing as a start time of 21:30 Eastern, which is 9:30 pm.  When in fact it started at 9:30 AM and is actually almost complete (as of 12:47 Eastern).  It appears the same thing is true for the London games in week 7 and 8.  

All other games have times that correctly convert between time zones.  I assume that all of these times are stored in UTC, so not sure where the conversion issue might be.

**Comment by BurntSushi** [comment]
The source data is impossible to interpret directly. It has to be overrided on a case by case basis.

I fixed it for this game this morning. Upgrade nfldb and run nfldb-update twice.
