### ISSUE TITLE
Can't seem to connect to db

### ISSUE THREAD

**Issue by cmorancie** [BurntSushi/nfldb#110]
Trying to use the escape hatch mentioned here "https://github.com/BurntSushi/nfldb/wiki/Installation" but can't seem to connect to db. Keep getting this error:

FATAL:  password authentication failed for user "nfldb_public".

Thanks for any help.

**Comment by BurntSushi** [comment]
It's not up and it was useless while it was. It's too slow to run a PostgreSQL database over the Internet.

I've removed it from the wiki. Sorry.

**Comment by cmorancie** [comment]
No need to apologize, it is a great thing you are doing here. Keep up the good work. I do a lot of work with creating synthetic APIs from web scraping with some pretty high level enterprise tools. Let me know if I can contribute in any way.
