### ISSUE TITLE
Broncos week 2 sacks

### ISSUE THREAD

**Issue by lark047** [BurntSushi/nfldb#112]
According to NFLDB the Broncos defense had 4 sacks against KC in week 2,

    nfldb=> select p.full_name, sum(pp.defense_sk)
    nfldb-> from play_player pp
    nfldb-> inner join player p using ( player_id )
    nfldb-> where pp.gsis_id = '2015091700' -- DEN@KC, week 2
    nfldb->   and pp.team = 'DEN'
    nfldb-> group by p.full_name
    nfldb-> having sum(pp.defense_sk) > 0
    nfldb-> order by 1;
    
     full_name      | sum
    ----------------+-----
     Antonio Smith  |   1
     DeMarcus Ware  |   1
     Malik Jackson  |   1
     Von Miller     |   1
    (4 rows)

whereas [GameCenter says](http://www.nfl.com/gamecenter/2015091700/2015/REG2/broncos@chiefs#menu=gameinfo|contentId%3A0ap3000000533404&tab=analyze&analyze=boxscore) they had 5.

**Comment by BurntSushi** [comment]
Upon discovering inaccuracies in the data, please try two things:

1. Delete the game from nfldb and nflgame. Then run nfldb-update.
2. If (1) doesn't fix it, then inspect the gamecenter JSON data manually and see if the inaccuracy exists there too. Looking at the web page is not sufficient.

**Comment by lark047** [comment]
It looks like `schedule.json` has the game information for nflgame, but how can I delete the game from nfldb?

**Comment by BurntSushi** [comment]
The `schedule.json` is just the schedule. It doesn't contain game data. You need to find the JSON data and delete the corresponding game.

`nfldb` is just a PostgreSQL database. All you need to do is delete the corresponding row from the game table: `DELETE FROM game WHERE gsis_id = '2015xxxxxxx'.

**Comment by lark047** [comment]
I claim "having a child in the last 2 years" for not getting how to delete from a database. SMH.

**Comment by lark047** [comment]
I removed the row

    nfldb=> delete from game where gsis_id = '2015091700';
    DELETE 1
    nfldb=>

and the GC JSON data

    aclark@asimov:/usr/local/lib/python2.7/dist-packages/nflgame/gamecenter-json$ rm -f 2015091700.json.gz

then ran `nfldb-update`, yet I still show only 4 sacks. Looking into the JSON data now.

**Comment by lark047** [comment]
I see only four sacks in the JSON data, too

    aclark@asimov:~$ cat 2015091700.json | sed 's/,/,\n/g' | grep -i sack | grep -v Manning
    "desc":"(4:45) (Shotgun) A.Smith sacked at KC 36 for -4 yards (D.Ware).",
    "desc":"(3:58) (Shotgun) A.Smith sacked at KC 31 for -5 yards (V.Miller). Penalty on KC-B.Grubbs,
    "desc":"(12:18) (Shotgun) A.Smith sacked at KC 22 for -8 yards (A.Smith).",
    "desc":"(:19) (Shotgun) A.Smith sacked at KC 27 for -4 yards (M.Jackson).",
    aclark@asimov:~$

**Comment by lark047** [comment]
Looks like this play is missing from the JSON data:

    2-7-DEN 14 (7:15) (Shotgun) 19-J.Maclin sacked at DEN 17 for -3 yards (30-D.Bruton).

**Comment by lark047** [comment]
Instead of the above description, NFLDB says

    nfldb=> select description from play where gsis_id = '2015091700' and play_id = 3567;
                                                                   description
    ------------------------------------------------------------------------------------------------------------------------------------------
     (7:15) (Shotgun) J.Maclin left end to DEN 17 for -3 yards (D.Bruton). A.Smith ran left, pitched to J.Maclin going right. Reversed field.
    (1 row)

and the JSON data:

`"desc":"(7:15) (Shotgun) J.Maclin left end to DEN 17 for -3 yards (D.Bruton). A.Smith ran left, pitched to J.Maclin going right. Reversed field.",`

**Comment by lark047** [comment]
Well, I guess [the data](http://www.nfl.com/liveupdate/game-center/2015091700/2015091700_gtd.json) from nfl.com is the real source of the mismatch. I'll try to contact the GC devs again,

**Comment by BurntSushi** [comment]
@lark047 How are you contacting the GC devs? Have you ever had any success?

**Comment by lark047** [comment]
I used the form at http://fantasy.nfl.com/feedback. Who knows if I'll ever hear anything. I'll let you know if they respond.

Will close this issue as it is not an NFLDB problem.

**Comment by BurntSushi** [comment]
@lark047 Yes, I wouldn't bother. There are *many* inaccuracies in the GC data. Moreover, we don't even know if the inaccuracies are intentional or a result of buggy code or a result of a hardware malfunction or a result of human error.
