### ISSUE TITLE
parsing <class 'nfldb.query.AggPP'>

### ISSUE THREAD

**Issue by chppppp** [BurntSushi/nfldb#113]
I run this:

```
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = gp
for key,value in NYGmisc.iteritems():
  print key,value
```

I get this:

```
Larry Donnell (NYG, TE) {'receiving_tds': 2L, 'receiving_yac_yds': 60L, 'fumbles_rec': 1L, 'receiving_rec': 21L, 'receiving_yds': 154L, 'receiving_tar': 30L}
<class 'nfldb.query.AggPP'>
Jerome Cunningham (NYG, TE) {'receiving_yac_yds': 1L, 'receiving_yds': 3L, 'receiving_tar': 3L, 'receiving_rec': 1L}
<class 'nfldb.query.AggPP'>
```

Now I want to parse that nested dict (which i know isnt really a dict):

```
NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = gp

for key,value in NYGmisc.iteritems():
  print key,value
  for k,v in value:
    print k,v

  File "app.py", line 64, in <module>
    for k,v in value.iteritems():
  File "/home/carrier/nfl1/local/lib/python2.7/site-packages/nfldb/types.py", line 1419, in __getattr__
    raise AttributeError(k)
```

If i try to value.iteritems() it throws an error. How can I parse that AggPP object?

**Comment by chppppp** [comment]
Also, why is #nflgame on Freenode dead? ;)

**Comment by BurntSushi** [comment]
I don't understand your question. Could you please describe the problem you're trying to solve? Also, please see the stat categories: https://github.com/BurntSushi/nfldb/wiki/Statistical-categories

**Comment by BurntSushi** [comment]
> Also, why is #nflgame on Freenode dead? ;)

It's not. But there's really only two people that answer questions (myself and @ochawkeye), and neither one of us is available 24/7 to do so.

**Comment by chppppp** [comment]
When I run this code:

NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = gp
for key,value in NYGmisc.iteritems():
  print key,value

I get these results (shortened):

Daniel Fells (NYG, TE) {'receiving_yac_yds': 37L, 'receiving_yds': 60L,
'receiving_tar': 7L, 'receiving_rec': 6L}

The value in the dict NYGmisc is a <class 'nfldb.query.AggPP'> object,
which *appears* to be a dictionary (formatted like
{'key1':value1,'key2':value2}) but when I try to parse it like a dict I get
an error. Here is my code and result:

NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = gp

for key,value in NYGmisc.iteritems():
  print key,value
  for k,v in value:
    print k,v

Traceback (most recent call last):
  File "app.py", line 64, in <module>
    for k,v in value:
TypeError: 'AggPP' object is not iterable

How can I iterate through an AggPP object like a regular python dict?

Thanks

**Comment by BurntSushi** [comment]
Use the [`fields`](https://github.com/BurntSushi/nfldb/blob/master/nfldb/types.py#L1278) method.

**Comment by chppppp** [comment]
Still erroring...I am sure I am making some newb mistake :/ Thank you!!

NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = gp

for key,value in NYGmisc.iteritems():
  print key,value
  for k,v in value.fields:
    print k,v

  File "app.py", line 64, in <module>
    for k,v in value.fields:
ValueError: too many values to unpack


NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = gp

for key,value in NYGmisc.iteritems():
  print key,value
  for k,v in value.fields():
    print k,v

  File "app.py", line 64, in <module>
    for k,v in value.fields():
TypeError: 'set' object is not callable

._fields or ._fields() yields

TypeError: 'NoneType' object is not callable

**Comment by ochawkeye** [comment]
Try `value.fields` instead of `value.fields()`.  `fields` is a property.  But `value.fields` is a set of the stat categories available for that play player.  It is not a stat category : stat value combination.

Could you explain more clearly what you are trying to do?

**Comment by chppppp** [comment]
NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = gp

for key,value in NYGmisc.iteritems():
  print key,value
  for ke,ve in value.fields:
    print ke,ve

$ python app.py
Larry Donnell (NYG, TE) {'receiving_tds': 2L, 'receiving_yac_yds': 60L,
'fumbles_rec': 1L, 'receiving_rec': 21L, 'receiving_yds': 154L,
'receiving_tar': 30L}
Traceback (most recent call last):
  File "app.py", line 64, in <module>
    for ke,ve in value.fields:
ValueError: too many values to unpack

In the code above, it creates a python dictionary NYGmisc[gp.player] = gp .
The values within that dict are AggPP that *appear* to be like a python
dict but I cannot iterate through it like a python dict.

To say it in other words, I want to take this:

Larry Donnell (NYG, TE) {'receiving_tds': 2L, 'receiving_yac_yds': 60L,
'fumbles_rec': 1L, 'receiving_rec': 21L, 'receiving_yds': 154L,
'receiving_tar': 30L}

and print it like

Larry Donnell (NYG, TE)
receiving_tds 2L
receiving_yac_yds': 60L
fumbles_rec': 1L
receiving_rec': 21L
receiving_yds': 154L
receiving_tar': 30L

**Comment by ochawkeye** [comment]
Oh, ok.

```python
for pp in q.play_player(team='NYG').player(position='TE').as_aggregate():
    print
    print pp.player
    for field in pp.fields:
        print field, getattr(pp, field)
```

**Comment by chppppp** [comment]
Thank you. I am now just trying to apply this to my dictionary.

Appreciate the fast response! Guessing you guys are watching the NYG/PHI
game too

**Comment by chppppp** [comment]
Forgive my noob-ness :)

Your answer does successfully print the data I want but I am hoping I can store the data in a dict so I can display it later in a Flask template. Any chance you folks could help me out with this code?

NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  for ke in gp.fields:
    NYGmisc[gp.player] = gp
    print ke

I still cannot iterate through the nested dict without getting an error "too many to unpack".

**Comment by ochawkeye** [comment]
Would you mind including all of the code necessary to get a working snippet?

**Comment by ochawkeye** [comment]
Taking a stab:

```python
import nfldb
NYGmisc = {}

db = nfldb.connect()
qNYG = nfldb.Query(db)
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
    # print
    # print gp.player
    # for field in gp.fields:
    #     print '{}: {}'.format(field, getattr(gp, field))
    for ke in gp.fields:
        # print ke
        NYGmisc[str(gp.player)] = {field: getattr(gp, field) for field in gp.fields}

print NYGmisc
```
```
{'Kellen Davis (NYJ, TE)': {'receiving_tds': 1L, 'receiving_yac_yds': 9L, 'defense_tkl': 1L, 'receiving_rec': 3L, 'receiving_yds': 12L, 'receiving_tar': 3L}, 'Daniel Fells (NYG, TE)': {'fumbles_tot': 1L, 'fumbles_forced': 1L, 'receiving_tds': 4L, 'fumbles_lost': 1L, 'receiving_yac_yds': 145L, 'defense_tkl': 1L, 'receiving_rec': 26L, 'receiving_yds': 306L, 'receiving_tar': 33L, 'defense_ast': 1L}, 'Will Tye (NYG, TE)': {'receiving_yac_yds': 32L, 'receiving_yds': 70L, 'receiving_tar': 8L, 'receiving_rec': 6L}, 'Brandon Myers (TB, TE)': {'receiving_tds': 4L, 'receiving_yac_yds': 196L, 'defense_tkl': 2L, 'receiving_rec': 52L, 'receiving_yds': 589L, 'receiving_tar': 82L}, 'Larry Donnell (NYG, TE)': {'fumbles_tot': 4L, 'fumbles_forced': 4L, 'receiving_tds': 8L, 'fumbles_lost': 4L, 'receiving_yac_yds': 402L, 'fumbles_rec': 1L, 'defense_frec': 1L, 'defense_tkl': 5L, 'receiving_rec': 107L, 'receiving_yds': 1002L, 'receiving_tar': 167L, 'kickret_ret': 1L, 'defense_ast': 4L}, 'Martellus Bennett (CHI, TE)': {'receiving_tds': 6L, 'receiving_yac_yds': 220L, 'kickret_yds': 13L, 'defense_tkl': 3L, 'receiving_rec': 62L, 'receiving_yds': 675L, 'receiving_tar': 98L, 'kickret_ret': 1L}, 'Scott Chandler (NE, TE)': {'receiving_yac_yds': 15L, 'receiving_yds': 26L, 'receiving_tar': 4L, 'receiving_rec': 2L}}
```

I think your problem is that you are talking about actually constructing a dictionary of dictionaries but your code doesn't reflect that.

**Comment by chppppp** [comment]
this worked for me:
NYGmisc = { }
for gp in qNYG.play_player(team='NYG').player(position='TE').as_aggregate():
  NYGmisc[gp.player] = {field: getattr(gp, field) for field in gp.fields}
for x in NYGmisc:
  for y in NYGmisc[x].iteritems():
    print y
@app.route("/")
def main():
    return render_template('index.html',thing10=NYGmisc)

and in my index.html template:

             <h4>nyg</h4>
                <p> <table>
                      {% for key in thing10 %}
                   <tr>
                   <th> {{ key }}  </th>
                        {% for ke in thing10[key].iteritems() %} 
                   <td>   {{ ke }}  </td>
                   </tr>
                        {% endfor %} 
                      {% endfor %}
                </table>  </p> 

This displays the data I want.
