### ISSUE TITLE
No module named pytz

### ISSUE THREAD

**Issue by CaldwellYSR** [BurntSushi/nfldb#116]
After following the installation instructions on a Mac I was unable to run the test file because of an import error saying pytz wasn't installed (it was). I was able to fix it using a suggestion from this link: http://stackoverflow.com/questions/30224539/pytz-install-on-mac

Once I installed it using python2 -m pip install pytz the test file ran correctly. Just thought I would throw this out there for anyone else that might be having a similar issue.

**Comment by ochawkeye** [comment]
Do you have multiple versions of Python on your system?  You state that
'pytz' was installed but then you fixed your problem by actually installing
'pytz'.

You need to actually be installing the dependencies in the version of
Python your 'nfldb' install lives in. By specifying "python2" you told your
system to install in your Python2 environment  (as opposed to presumably
Python3 where your initial install probably ended up).

**Comment by CaldwellYSR** [comment]
I do have multiple versions of python and I originally thought that was the issue so I tried running pip2 to install it in the right place and this is what I got:

=> pip2 install nfldb
Requirement already satisfied (use --upgrade to upgrade): nfldb in /Library/Python/2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): psycopg2 in /Library/Python/2.7/site-packages (from nfldb)
Requirement already satisfied (use --upgrade to upgrade): pytz in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from nfldb)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /Library/Python/2.7/site-packages (from nfldb)
Requirement already satisfied (use --upgrade to upgrade): nflgame>=1.2.10 in /Library/Python/2.7/site-packages (from nfldb)
Requirement already satisfied (use --upgrade to upgrade): httplib2 in /Library/Python/2.7/site-packages (from nflgame>=1.2.10->nfldb)
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /Library/Python/2.7/site-packages (from nflgame>=1.2.10->nfldb)

pytz is in there and in the 2.7 dir like all the others. I looked through tons of issue threads on here and didn't find anything. Not sure why the above worked when the rest didn't but it's working now.

**Comment by BurntSushi** [comment]
@CaldwellYSR Notice that `pytz` is actually in your `/System` directory, unlike the rest of the libraries, which are in `/Library`. When you ran `python2 pip` instead of `pip` by itself, then you probably used a different installation of Python that doesn't use `/System`.

Python packaging is hard because failure modes are nearly impossible to decipher. It sucks and there's really nothing we can do about it. The best advice I can give is "stick to virtualenvs and never look back."

**Comment by CaldwellYSR** [comment]
Sorry for reopening this but I wanted to say that I looked up virtualenvs and now I understand! It was an issue where I had pytz for the wrong installation of python.

**Comment by weissleb** [comment]
I was having the same issue, where pytz was installed in the wrong place and I couldn't fix it.  The accepted solution at https://stackoverflow.com/questions/35049907/cannot-sudo-pip-uninstall-operation-not-permitted-tmp-in-os-x-el-capitan did the trick!

Hint:
`brew reinstall python@2`
`pip2 install --user nfldb`
