### ISSUE TITLE
D.Saunders has no player information listed.

### ISSUE THREAD

**Issue by rtconner** [BurntSushi/nfldb#119]
There is a player who is listed as playing in this weeks Browns/Bengals game 00-0031917. The player record for him has no first or last name and his team and position are UNK.

**Comment by ochawkeye** [comment]
Have you run `nfldb-update` since that player appeared?

```python
import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2015, season_type='Regular')
q.player(gsis_name='D.Saunders')
for player in q.as_players():
    print player.full_name
    print player.player_id
```
```bash
De'Ante Saunders
00-0031917
```

**Comment by rtconner** [comment]
Yeah I have it on the daemon to run every 30 seconds. Weird. I guess if it's just me having this issue it's not a bug. I wonder what I have configured wrong.

**Comment by BurntSushi** [comment]
Try deleting the player entry from `nflgame`'s players.json file and then re-running `nflgame-update-players`. Finally, run `nfldb-update --player-interval 0`.

Player meta data retrieval can't be expected to always be correct, sorry. We have to be careful not to hit nfl.com a lot, so it might have stale data and there really isn't a reliable way to know to re-check.

**Comment by rtconner** [comment]
That seems to have fixed the issue. Ok I'll just remember to run that next time this happens.

"We have to be careful not to hit nfl.com a lot" -- Yeah I was really wondering about this. Does 'nfldb-update --interval 30' hit their server every 30 seconds? Should I find a way to turn that off on non-game days?

**Comment by BurntSushi** [comment]
@rtconner You shouldn't have to worry about any of that by default. It is smart and doesn't always hit the server when games aren't playing. When games are playing, it does hit nfl.com every 30 seconds, but that should be just fine. (You'll use less bandwidth than someone who has the GameCenter page open in a tab, which refreshes even more frequently than that.)

**Comment by rtconner** [comment]
Ok thank you. And thank you for making this project.
