### ISSUE TITLE
Yahoo league

### ISSUE THREAD

**Issue by Coach81** [BurntSushi/nfldb#123]
Greetings,
Sorry if I posted in the wrong place. I've been using nfldb since the beginning of the season.  Still trying to get the hang of it.  Is there a way to import the roster of my Yahoo league?  I see you have a project called nflfan.  Do they share the same database?  I would be interested in adding the roster table to the same db holding all of the nfl data.
Thanks

**Comment by BurntSushi** [comment]
`nfldb` is not a fantasy football project. It never was and never will be. That said, you can certainly use it in fantasy football projects.

`nflfan` is a single user web application. Its Yahoo importer broke this year (it still works for public leagues, but not for private leagues). I don't know when or if I'll fix it. `nflfan` does not store things in the database. Instead, it stores roster info (among other things) in JSON files on disk.

Questions about `nflfan` should be on its issue tracker. Please open an issue there if you want to continue this discussion! Thanks.
