### ISSUE TITLE
Why does my for loop return the same first value X times rather than unique values?

### ISSUE THREAD

**Issue by mcluffin** [BurntSushi/nfldb#125]
This isn't an issue per se, but a programming question I'm hoping to get some help with. I also posted it on stackoverflow:

http://stackoverflow.com/questions/34232734/why-does-my-python-for-loop-return-the-same-first-value-x-times-rather-than-uniq

When I run this code:

import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
for i in range (1,15):
    q.game(season_year=2015, season_type='Regular', week=i)
    q.player(full_name='Julian Edelman')
    print p.player.full_name, p.receiving_yds, p.receiving_tds

It returns Edelman's first week stats 14 times, rather than each week's stats as expected. However, if I run the code for each individual week (week=1; week=2; and so on) it returns the expected results, individually. I'm a beginner with Python/Postgres so pardon my ignorance to any language-specific behaviour I'm unfamiliar with.

**Comment by ochawkeye** [comment]
The code you have posted (even with corrected indenting) will not run.  Could you please check that and re-post?

You can wrap your code in 3 tickmarks (the key that makes a tilde ~ if you press SHIFT+`)

**Comment by ochawkeye** [comment]
You're not really thinking about these queries properly.

When you do `q = nfldb.Query(db)` you are telling nfldb that you are making a new query on the entire database.  When you follow that with `q.game(season_year=2015, season_type='Regular', week=1)` you are telling nfldb that you are only interested in week 1 so it can throw everything else away.  When you follow that your next time through the loop with `q.game(season=2015, season_type='Regular', week=2)` you are asking nfldb to access a week that you just told it to throw away a minute ago.

If you really want to look at a week you're already told nfldb to discard, then you'll have to tell nfldb that you want to make a new query.

```python
import nfldb
db = nfldb.connect()
for i in range (1,15):
    q = nfldb.Query(db)
    q.game(season_year=2015, season_type='Regular', week=i)
    q.player(full_name='Julian Edelman')
```

**Comment by mcluffin** [comment]
Thank you kindly for your quick response. Here is your working code along with output:

```import nfldb
db = nfldb.connect()
for i in range (1,15):
    q = nfldb.Query(db)
    q.game(season_year=2015, season_type='Regular', week=i)
    q.player(full_name='Julian Edelman')
    for p in q.sort('receiving_yds').as_aggregate():
        print p.player.full_name, p.receiving_yds, p.receiving_tds```

Julian Edelman 97 0
Julian Edelman 97 2
Julian Edelman 85 0
Julian Edelman 120 1
Julian Edelman 50 1
Julian Edelman 54 0
Julian Edelman 81 2
Julian Edelman 55 1
Julian Edelman 53 0
