### ISSUE TITLE
Can't update nfldb

### ISSUE THREAD

**Issue by scarrick68** [BurntSushi/nfldb#126]
everything from this installation instructions is working up to running nfldb-update. I get the following message:

-------------------------------------------------------------------------------
STARTING NFLDB UPDATE AT 2015-12-12 23:14:16.237569
Connecting to nfldb... done.
Setting timezone to UTC... done.
Locking write access to tables... done.
Updating season phase, year and week... done.
Bulk inserting data for 87 games...
Could not cache JSON data. Please make '/usr/local/lib/python2.7/dist-packages/nflgame/gamecenter-json' writable.
Could not cache JSON data. Please make '/usr/local/lib/python2.7/dist-packages/nflgame/gamecenter-json' writable.
Could not cache JSON data. Please make '/usr/local/lib/python2.7/dist-packages/nflgame/gamecenter-json' writable.
Could not cache JSON data. Please make '/usr/local/lib/python2.7/dist-packages/nflgame/gamecenter-json' writable.
Could not cache JSON data. Please make '/usr/local/lib/python2.7/dist-packages/nflgame/gamecenter-json' writable.
        Sending batch of data to database.

Everything after "bulk inserting data for 87 games" repeats itself over and over. I have tried giving write permission to the gamecenter-json folder with 'sudo chmod +w gamecenter-json/' and 'sudo chmod u+w gamecenter-json/' but I get the same error messages.

EDIT: It seems like the db updates, but just doesn't cache the JSON data. If run with sudo, everything is fine.

**Comment by BurntSushi** [comment]
The only explanation I can think of is that your `chmod` command is either failing or you're applying it to the wrong directory. The error message is pretty straight-forward: if it can't write JSON data to the directory shown, then it shows the error. It's really up to you to make the directory writeable.

A better solution might be to install `nflgame` into a `virtualenv`, or install with pip with the `--user` flag.
