### ISSUE TITLE
Division, Conference

### ISSUE THREAD

**Issue by mrg1999** [BurntSushi/nfldb#127]
Given a team name or team ID, is there a way to extract their conference and division from the nfldb database?

**Comment by BurntSushi** [comment]
No. There are only 32 teams and their conference/division membership rarely changes. (The last time anything was what, at least ten years ago?)

Just create a map in your source code and use that.

**Comment by BurntSushi** [comment]
I guess we could add it to the `team` table. Wouldn't be too big of a deal. Should be stored here: https://github.com/BurntSushi/nfldb/blob/master/nfldb/team.py

**Comment by mrg1999** [comment]
That would be perfect as I'm alread using the team Table to get the Names, IDs and Cities.
Divisions & conferences would be useful for division & conference records as well as displaying league standings.
