### ISSUE TITLE
Wrong score (DAL @ GB)

### ISSUE THREAD

**Issue by skaren** [BurntSushi/nfldb#128]
I get a wrong score at the game DAL @ GB from last Sunday.

```
Regular 2015 week 14 on 12/13 at 10:25PM, DAL (0) at GB (14)
```

The correct score is DAL 7 : 28 GB.

This is my search query:

```
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)

q.game(season_year="2015", week="14", season_type="Regular", home_team="GB")
for game in q.as_games():
   print game
```

**Comment by lark047** [comment]
You should probably run `nfldb-update`

```
$ cat game.py
import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year="2015", week="14", season_type="Regular", home_team="GB")
for game in q.as_games():
  print game
$ python game.py
Regular 2015 week 14 on 12/13 at 04:25PM, DAL (7) at GB (28)
$
```

**Comment by ochawkeye** [comment]
That actually won't help in this case.  See: https://github.com/BurntSushi/nflgame/issues/185

NFL.com flagged this came as Finished at halftime, so `nflgame` saw that and cached it.  It isn't ever going to bother to go back and re-lookup finished games.  So you'll have to delete that record `2015121313.json.gz` out of `nflgame/gamecenter-json`.

After doing that, you can run `nfldb-update` and the game will cache in its entirety.

**Comment by skaren** [comment]
If I use `nfldb-update --update-schedules` it download the record `2015121313.json.gz` again and set a new timestamp `time_updated` in database, but the score is still the same.

**Comment by BurntSushi** [comment]
You need to delete `2015121313.json.gz` manually. Nothing else will ever delete it. Then you need to deleted the `nfldb` record: `DELETE FROM game WHERE gsis_id = '2015121313';`.

**Comment by skaren** [comment]
The correct ID for the game is `2015121312`.

It works after deleting `2015121312.json.gz` and `DELETE FROM game WHERE gsis_id = '2015121312';`.

Thank you all for the support.
