### ISSUE TITLE
Anyone know how to query for play by play results by down?

### ISSUE THREAD

**Issue by BlackArbsCEO** [BurntSushi/nfldb#131]
Was going over the nfldb data model but did not see any obvious way to do this. I'm looking to query play results by down. For example, how would I query something like NE Patriots, week 10, all 1st down plays? or NE Patriots all 3rd down and short plays?

**Comment by BurntSushi** [comment]
Use the `down` and `yards_to_go` fields with the `Query.play` method. They should be documented in the [statistical categories](https://github.com/BurntSushi/nfldb/wiki/Statistical-categories#play-statistics) page, but it seems they are missing. They are however documented in the [API documentation](http://pdoc.burntsushi.net/nfldb#nfldb.Play).

**Comment by BurntSushi** [comment]
Those fields are also included in the ER diagram found in the [data model](https://github.com/BurntSushi/nfldb/wiki/The-data-model) page.

**Comment by BlackArbsCEO** [comment]
Thanks for the quick response and for pointing that out. Do the greater than/less than operators work for for yards_to_go or is there a workaround? Right now, this works:
```
db          =  pg.connect(dbname = 'nfldb', user = 'postgres', password = 'password', port ='port_num')
season_year = 2015
season_week = 15

tm = 'NE'
q = nfldb.Query(db)
q.game(season_year=season_year, season_type='Regular', week = season_week, team = tm)
q.play(down=3, yards_to_go=3)
for p in q.as_plays():
    print(p)
```
But I only see the comparison operators used for the `play_player` method and an error is generated when I use it for the `play` method.

**Comment by BurntSushi** [comment]
Please show the code that doesn't work and the output that it produces.

**Comment by BlackArbsCEO** [comment]
Man I feel slow this morning, may need more coffee. I forgot to add the additional underscore:

```
tm = 'NE'
q = nfldb.Query(db)
q.game(season_year=season_year, season_type='Regular', week = season_week, team = tm)
q.play(down=3, yards_to_go_le=3) # <--- causes error
for p in q.as_plays():
    print(p)

tm = 'NE'
q = nfldb.Query(db)
q.game(season_year=season_year, season_type='Regular', week = season_week, team = tm)
q.play(down=3, yards_to_go__le=3) # <--- works as expected
for p in q.as_plays():
    print(p)
```

**Comment by BurntSushi** [comment]
Glad you got it figured out! :-)
