### ISSUE TITLE
Link to Postgres installation instructions for mac on wiki is dead

### ISSUE THREAD

**Issue by dansbecker** [BurntSushi/nfldb#135]
The wiki currently links to http://russbrooks.com/2010/11/25/install-postgresql-9-on-os-x for installation of postgres on a mac.  As of Jan 6, 2016 this link appears to be dead.

**Comment by ochawkeye** [comment]
Fixed by prepending `www.` to [link](http://www.russbrooks.com/2010/11/25/install-postgresql-9-on-os-x)
