### ISSUE TITLE
Different values to espn.com

### ISSUE THREAD

**Issue by skaren** [BurntSushi/nfldb#138]
Does somebody has any idea why i get different values in the database to espn.com (same at nfl.com)?
Is there a function to update all values in the database?

<img width="1216" alt="160116132508" src="https://cloud.githubusercontent.com/assets/2912000/12372421/70bb84be-bc56-11e5-9b5b-cf61efbd28d7.png">

**Comment by BurntSushi** [comment]
@skaren The GameCenter JSON data (the source for all of nfldb's data) is not 100% accurate. That is the most likely cause.
