### ISSUE TITLE
Kickers missing PAT attempts and made

### ISSUE THREAD

**Issue by mikemacgregor** [BurntSushi/nfldb#139]
In trying to understand the database structure I've been simply querying the database and then comparing to posted stats to see if my queries are correct. All looks pretty good until I ran into ... kickers PATs. Damn kickers! This:

```
>>> import nfldb
>>> db = nfldb.connect()
>>> q = nfldb.Query(db)
>>> q.game(season_year=2015, season_type='Regular')
<nfldb.query.Query object at 0x101fb7e10>
>>> for pp in q.sort('kicking_xpmade').limit(10).as_aggregate():
...     print pp.player, pp.kicking_xpmade
```
produced this:

```
Graham Gano (CAR, K) 52
Stephen Gostkowski (NE, K) 50
Chandler Catanzaro (ARI, K) 47
Mike Nugent (CIN, K) 47
Josh Brown (NYG, K) 40
Steven Hauschka (SEA, K) 37
Sebastian Janikowski (OAK, K) 37
Dustin Hopkins (WAS, K) 36
Mason Crosby (GB, K) 34
Matt Prater (DET, K) 34
```
Gostkowski had 52 PAT made. Gano had 56 made.

Here is what I noticed on Gostkowski... when I did a game by game query he was missing one from Week 15 and one from Week 16. In each of those games, the Pats scored a defensive TD, their only 2 of the season.

Gano should have 56 but has 52, missing 4. Panthers scored 5 defensive TD during the season so that doesn't quite work there.

Catanzaro is short 6 XP Made and the Cards D scored 6 defensive TD.

Anyone else notice this and/or is the database recording these PAT a different way that I'm just not realizing? Of course the stats on NFL.com for each of these kickers is correct, so feel like I'm missing something in querying the PATs on a defensive TD, or something else.

**Comment by ochawkeye** [comment]
Yep.  See [here](https://github.com/BurntSushi/nfldb/issues/106), [here](https://github.com/BurntSushi/nfldb/issues/70), [here](https://github.com/BurntSushi/nflgame/issues/188), and [here](https://github.com/BurntSushi/nflgame/issues/112).

Unfortunately, it is the source JSON data from NFL.com that is missing the PATs following a defensive score.  `nflgame` tries to fill in the gaps heuristically for game level statistics (game.[`max_player_stats`](https://github.com/BurntSushi/nflgame/blob/cda547246f5de32363fad349dde434808447189e/nflgame/game.py#L353)), but as there are no such equivalent game level statistics in `nfldb` (game statistics are aggregated play statistics) it is not something ported here.
