### ISSUE TITLE
Best way to get a list of all players

### ISSUE THREAD

**Issue by cwebz** [BurntSushi/nfldb#145]
Hi, so I am new to diving deep into your awesome nfldb. I haven't worked with python or pregsql so excited to learn a new language. I want to get a list of all players from 2015 at the positions (QB,RB,WR,TE). I am looking over the api documentation and still looking but what would be the most efficient way of doing this?

Thanks so much for this, this is awesome and excited to work with the data

**Comment by andr3w321** [comment]
I prefer working directly with SQL. I'm on my phone so can't look up the exact query but something like 'SELECT player_id, first_name, last_name FROM player WHERE position = 'QB' OR position = 'RB' OR position = 'TE' OR position = 'WR'' should work

**Comment by ochawkeye** [comment]
```python
import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2015, season_type='Regular')
for pp in q.as_aggregate():
    if str(pp.player.position) in ['QB', 'RB', 'WR', 'TE']:
        print pp.player
```

```bash
...
T.J. Yeldon (JAC, RB)
Tyler Lockett (SEA, WR)
Tyler Kroft (CIN, TE)
Dorial Green-Beckham (TEN, WR)
Todd Gurley (STL, RB)
Sean Mannion (STL, QB)
Kasen Williams (SEA, WR)
Clive Walford (OAK, TE)
Duke Johnson (CLE, RB)
Marcus Mariota (TEN, QB)
```

**Comment by cwebz** [comment]
Thank you both very much. I am a fan of just doing sql queries as well, but these are both great options and have been of great help.

One last question I am using postgresql 9.3, does upgrading to 9.5 have any effect on anything?

**Comment by BurntSushi** [comment]
9.5 should be fine.
