### ISSUE TITLE
DB download too large

### ISSUE THREAD

**Issue by chadwilcomb** [BurntSushi/nfldb#152]
This project looks fantastic, I wanted to download the Postgres database at the bottom of the README, but I get the following error:

The file you have attempted to download is too large. There is a 10MB limit on downloads.

Generated Wed, 27 Apr 2016 00:25:32 GMT by cache_server (squid/2.6.STABLE21)

**Comment by BurntSushi** [comment]
I don't know where that error message is coming from, but it certainly isn't on my end. It downloads just fine.

I'm not sure what's wrong, sorry.

**Comment by chadwilcomb** [comment]
Oh, sorry, I am on Amtrak right now. I looked in the console and there weren't any redirects or anything, but it must be some limits on the WiFi. Sorry about that.

Looking forward to checking this out!

**Comment by chadwilcomb** [comment]
Yep, confirmed download works fine when not on Amtrak
