### ISSUE TITLE
Missing divisional and conference championship games?

### ISSUE THREAD

**Issue by tstewart15** [BurntSushi/nfldb#153]
I ran nfldb-update for the first time since Week 16 regular season of this year, and I've found that the divisional (2nd) round and the conference championship (3rd) round of the Postseason are missing (Week 17, wild card, and super bowl are showing up). Is this due to bad NFL GameCenter data? Or is there something corrupt in my database?

**Comment by danielcroona** [comment]
This is probably related to issue [#136 ](https://github.com/BurntSushi/nfldb/issues/136)

**Comment by tstewart15** [comment]
See solution in #136
