### ISSUE TITLE
2016 Schedule 

### ISSUE THREAD

**Issue by maa42** [BurntSushi/nfldb#161]
When will the  2016 schedule become available?

**Comment by ochawkeye** [comment]
If you manually flip-flop the schedule back to the regular season URL in file `..\nflgame\live.py` (uncomment line 68 `_CUR_SCHEDULE = "http://www.nfl.com/liveupdate/scorestrip/ss.xml"` & comment out line 75 `_CUR_SCHEDULE = http://www.nfl.com/liveupdate/scorestrip/postseason/ss.xml"`)

Then if you run `nfldb-update` the games should appear.

```python
import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2016, season_type='Regular', week=1)

for game in q.as_games():
    print game
```
```bash
Regular 2016 week 1 on 09/12 at 09:20PM, UNK (0) at SF (0)
Regular 2016 week 1 on 09/12 at 06:10PM, PIT (0) at WAS (0)
Regular 2016 week 1 on 09/11 at 07:30PM, NE (0) at ARI (0)
Regular 2016 week 1 on 09/11 at 03:25PM, DET (0) at IND (0)
Regular 2016 week 1 on 09/11 at 03:25PM, NYG (0) at DAL (0)
Regular 2016 week 1 on 09/11 at 03:05PM, MIA (0) at SEA (0)
Regular 2016 week 1 on 09/11 at 12:00PM, MIN (0) at TEN (0)
Regular 2016 week 1 on 09/11 at 12:00PM, CLE (0) at PHI (0)
Regular 2016 week 1 on 09/11 at 12:00PM, CIN (0) at NYJ (0)
Regular 2016 week 1 on 09/11 at 12:00PM, OAK (0) at NO (0)
Regular 2016 week 1 on 09/11 at 12:00PM, SD (0) at KC (0)
Regular 2016 week 1 on 09/11 at 12:00PM, GB (0) at JAC (0)
Regular 2016 week 1 on 09/11 at 12:00PM, CHI (0) at HOU (0)
Regular 2016 week 1 on 09/11 at 12:00PM, BUF (0) at BAL (0)
Regular 2016 week 1 on 09/11 at 12:00PM, TB (0) at ATL (0)
Regular 2016 week 1 on 09/08 at 07:30PM, CAR (0) at DEN (0)
```

**Comment by ochawkeye** [comment]
When [nflgame PR](https://github.com/BurntSushi/nflgame/pull/205) accepted, this manual modification will not be necessary.

**Comment by maa42** [comment]
Thanks. I was able to make the change but I only received 1 pre-season game.   http://www.nfl.com/liveupdate/scorestrip/ss.xml    actually only returns 1 game.

**Comment by ochawkeye** [comment]
Might be a case where `nflgame` isn't updating the schedule because it already [tried to update it less than a day ago](https://github.com/BurntSushi/nflgame/blob/master/nflgame/sched.py#L35)?

Can try running `..\Python27\Lib\site-packages\nflgame\update_sched.py --rebuild`

**Comment by maa42** [comment]
I figured out my issue.  I needed to run update_sched.py --year 2016 --phase REG before the db update.

Thanks for help

**Comment by mesee298** [comment]
I'm not using nfldb (I know I should be) and I'm unable to get the schedule.json to update for 2016.  I've tried to run update_schedule.py --year 2016 with and without --phase REG and I can get it to work.  Other ideas?

**Comment by BurntSushi** [comment]
Should be fixed.
