### ISSUE TITLE
I just want to download the 2015 NFL stats by player by week, is this the best place to go?

### ISSUE THREAD

**Issue by walkerstorrer** [BurntSushi/nfldb#162]
Hello, I want to download the 2015 NFL stats by player by week and import them into SQL Server 2016. I spent some time reading through this nfldb, but I'm concerned by the complexity of the steps (I'm not familiar with Python or Pip). This appears to be meant for "real-time" updates, which is a bit overkill for what I'm trying to do. Mind you, this is all for a personal project and not something that I hope to monetize. Is this the best place for me to get what I'm looking for?

**Comment by BurntSushi** [comment]
It is indeed meant to be for real time updates, but the complexity of that is in the `nfldb-update` script, not the schema. If you follow the directions in the wiki to get a PostgreSQL database running, then you can play with the data all you want in SQL land without caring much about Python. (You'll need to install Python and run `nfldb-update`, sure, but you shouldn't need to touch the code.) Assuming you're familiar with SQL Server, it shouldn't be that much of a jump to get basic familiarity with PostgreSQL.

**Comment by walkerstorrer** [comment]
Okay, thanks for the response. So there isn't a set of CSV files that could be quickly downloaded?

**Comment by BurntSushi** [comment]
You could set up the DB and then export the data as CSV.

**Comment by walkerstorrer** [comment]
Well, I'm wondering if there is a way to avoid setting up the DB on PostgreSQL and just download CSV files that you have posted here. I love the work that's done here, and I can appreciate the complexity of it and the detailed documentation that's provided, but a set of CSV files could revolutionize the accessibility of this data.

**Comment by BurntSushi** [comment]
@walkerstorrer There are no CSV files anywhere. The source data is a JSON feed on NFL.com, so I'm not holding anything back. I'm personally not interested in maintaining a CSV data dump. Others certainly are welcome to though!

**Comment by walkerstorrer** [comment]
Fair enough. I just want to stress how much more accessible this data becomes when it is presented as CSVs. For people without experience working in the Command Prompt or working with scripts, there's a lot to learn before you can get your hands on the data. Learning those things may be useful for some people, but I imagine many people could learn a ton by just working with the data. There are currently high barriers to entry for those people who just want to work with the data. Just my two cents. I think I'll look elsewhere, but if I can't find the simple solution I'm looking for I'll invest the time necessary to understand this.

**Comment by BurntSushi** [comment]
My goal is not to become a data repository. My goal is to provide software, tools and documentation for processing NFL data. If **someone else** wants to become a data repository based on `nfldb`, then I'd happily encourage that and link to it. If you'd like to take up that role, I'd be happy to mentor it.

**Comment by walkerstorrer** [comment]
Okay, I can respect that. It was just a suggestion to expand those goals, but you have far more experience than me and you obviously know what is best for you. As I mentioned, my goal is to better my SQL/data viz skills, and not to spend time learning scripts, etc. No sense trying to align diverging goals; [this](http://armchairanalysis.com/data.php) seems like a better resource for my needs.

**Comment by BurntSushi** [comment]
Yes, sorry, I don't have the extra time or desire to expand those goals. Others may. Good luck!
