### ISSUE TITLE
Games Played by a Player in A Season

### ISSUE THREAD

**Issue by travisscone** [BurntSushi/nfldb#163]
I am looking for a way to query the database and return the # of games a player played in for any given season. Anyone found a way to do this? Thanks in advance!

**Comment by ochawkeye** [comment]
If you are looking for a specific player, you could do something like the following (from https://github.com/BurntSushi/nflgame/issues/69)

```python
import nfldb

db = nfldb.connect()
q = nfldb.Query(db).game(season_year=2013, season_type='Regular')
print len(q.player(full_name='Shane Vereen').as_games())
```

Keep in mind this is not guaranteed to be the number of games a player played in - only the number of games a player recorded a statistic in.

**Comment by linkinpaak** [comment]
This is a quasi duplicate of https://github.com/BurntSushi/nflgame/issues/125 in which @BurntSushi explains how this isn't possible with this API.

**Comment by travisscone** [comment]
Thanks for the help. This is all my first exposure to python. 
I also have this sql which does the same thing: 
SELECT p.full_name,
COUNT( DISTINCT pp.gsis_id) as "Games Played"
FROM play_player pp
LEFT JOIN game g ON pp.gsis_id = g.gsis_id
LEFT JOIN player p ON p.player_id = pp.player_id 
WHERE g.season_type = 'Regular' AND g.season_year=2015
GROUP BY p.full_name
ORDER BY p.full_name ASC;
