### ISSUE TITLE
Season Year 2015

### ISSUE THREAD

**Issue by artl603** [BurntSushi/nfldb#164]
Hi, I don't see all the 2015 season post season games in the DB, there are only 5 of them.  Any thoughts?

Thanks.

**Comment by ochawkeye** [comment]
Try rebuilding the schedule file with

`/site-packages/nflgame/update_sched.py --rebuild --year 2015 --phase POST`

After that is run, you should be able to run `nfldb-update` as normal.

https://github.com/BurntSushi/nfldb/issues/136

**Comment by artl603** [comment]
That fixed it.

Thanks

**Comment by mrg1999** [comment]
ochawkeye
I wasn't getting any of postweek 1 scores so I ran your script and it fixed it.
Question: will I need to run this every week during the post season?
Thanks!
