### ISSUE TITLE
Turnovers for team is incorrect.

### ISSUE THREAD

**Issue by DylanModesitt** [BurntSushi/nfldb#166]
I saw a ticket similiar to this <a href="https://github.com/BurntSushi/nfldb/issues/98">here.</a> I am having trouble getting accurate statistics for getting the <i> average </i> turnovers involving a team per game (both turnovers committed and caused). 

As an example, I tried writing two different style of methods to get the total turnovers generated by a team in a season (regular).

Here are my results (the following are inside a `Team` class) :

```
def turnovers_in_season(self):
    q = nfldb.Query(db)
    q.game(season_year=self.year, season_type=self.season_type, team=self.team)
    # get the turnovers commited
    q.play(pos_team__ne=self.team)

    turnovers = nfldb.QueryOR(db).play(defense_int__ge=1, defense_frec__ge=1)
    q.andalso(turnovers)
    return len(q.as_plays())

```
The above method returns 23 when self.team = 'NE', self.season_year = 2015, and self.season_type = 'Regular'

```
def turnovers_in_season(self):
        q = nfldb.Query(db)
        q.game(season_year=self.year, season_type=self.season_type, team=self.team)
        # An important line! Without it, you'll get values from both teams.
        q.play_player(team=self.team)

        gs = q.as_games()
        sum = 0.0
        for g in gs:
            if g.home_team == self.team:
                print g.week, g.home_team, g.home_turnovers
                sum += g.home_turnovers
            else:
                print g.week, g.away_team, g.away_turnovers
                sum += g.away_turnovers
        return sum
```

The above method returns 24 when self.team = 'NE', self.season_year = 2015, and self.season_type = 'Regular'

Not only are these numbers different from each other, they seem to be different from the actual number which I believe is 21 according to <a href="http://espn.go.com/nfl/statistics/team/_/stat/givetake"> this source.</a>

I want to mention I am new to this API and I am not even a python dev. Am I doing something wrong? Is the data inaccurate? Is there a better query to get more accurate results? Thanks!

**Comment by BurntSushi** [comment]
`home_turnovers` and `away_turnovers` come from a different data source than from computing interceptions/fumbles straight from play-by-play data. Namely, the former are aggregate statistics straight from NFL.com. As such, there's no guarantee that they are the same.

Unfortunately, the data in general isn't 100% accurate.

**Comment by DylanModesitt** [comment]
Would you recommend the `home_turnovers`/`away_turnover` approach or the play-by-play approach? What would you do?

**Comment by BurntSushi** [comment]
@DylanModesitt If I really cared about accuracy, I would do an experiment and compare `home_turnovers`/`away_turnovers` with the aggregated statistics and see which was more accurate (which requires a third known-good source). Unfortunately, I've never done that particular experiment, so I can't answer your question.

**Comment by DylanModesitt** [comment]
I think _(with some limited research and testing)_ that the following produces the most accurate turnover results: 

```
def get_turovers_in_season(team, season_year, season_type, offensive):
    q = nfldb.Query(db)
    q.game(season_year=year, season_type=season_type, team=team)

    # Get values from the proper team requested
    if offensive:
        q.play_player(team=self.team)
    else:
        q.play_player(team__ne=self.team)
    pps = q.as_aggregate()
    return sum(pp.passing_int + pp.fumbles_lost for pp in pps)

```

Of course it is very hard to determine which strategy is most accurate. But this seems to work out pretty well.
