### ISSUE TITLE
Determining which team a penalty was against

### ISSUE THREAD

**Issue by joshutt** [BurntSushi/nfldb#173]
I don't see a way to determine which team a penalty was against.  The play table has columns for penalty, penalty_first_down and penalty_yds, but it's not obvious how to determine which team committed the penalty, short of grabbing the next play and seeing if the yardline is increased or decreased from the previous.  

Am I just missing something or was this an oversight?

**Comment by BurntSushi** [comment]
There's no oversight. There's simply very limited structured data on penalties from NFL.com. What you see is what you get.

If you really need this, then you are indeed limited to heuristics such as context of the play and the human readable play description text.
