### ISSUE TITLE
QUERY: 2nd and 10 passes after 1st down inc pass

### ISSUE THREAD

**Issue by robertromeo5** [BurntSushi/nfldb#174]
Hello, I'm trying to write a query that will grab the amount of times a team ran the ball on 2nd and 10 after throwing an incomplete pass on 1st down.

I'm able to successfully query the list of teams and how many times each ran on 2nd and 10, however because play_id is not sequential, I'm unable to figure out how many times they ran on 2nd and 10 after an incomplete 1st down pass.

I'm an amatuer SQL user, but maybe one of you can help?  Is there even a way to do this?

Here was my attempt when I assumed play_id was sequential (i.e. 1st down play_id = 1, 2nd down play_id =2.  Unfortunately my assumption was wrong and this is not the case).  If you comment out the following line: '
where second.play_id = first.play_after' you'll get inaccurate data as their can be more than one 2nd and 10 on the same drive and more than one 1st down incomplete pass in a drive.

select
				second.team as team			
,			sum(second.rush_att) as "rush att after 1st and 10 inc pass"
from
	(
	select
					play.pos_team as team
	,				play.down as down
	,				agg_play.gsis_id as gsis_id
	,				agg_play.drive_id as drive_id
	,				agg_play.play_id as play_id
	,				(agg_play.play_id - 1) as play_before
	,				agg_play.rushing_att as rush_att
	,				agg_play.passing_att as pass_att
	from agg_play
	join play on play.play_id = agg_play.play_id 
	and play.drive_id = agg_play.drive_id
	and play.gsis_id = agg_play.gsis_id
	join game on game.gsis_id = agg_play.gsis_id
	where game.season_type = 'Regular'
		AND game.season_year IN (2009,2010,2011,2012,2013)
		AND play.down IN (2)
		AND agg_play.rushing_att = 1
		AND play.yards_to_go = 10
	)second
 join
	(
	select
					play.pos_team as team
	,				play.down as down
	,				agg_play.gsis_id as gsis_id
	,				agg_play.drive_id as drive_id
	,				agg_play.play_id as play_id
	,				(agg_play.play_id + 1) as play_after
--	,				agg_play.rushing_att as rush_att
	,				agg_play.passing_att as pass_att
--	,				agg_play.passing_cmp as pass_cmp
	,				agg_play.passing_incmp as pass_incmp
	from agg_play
	join play on play.play_id = agg_play.play_id 
	and play.drive_id = agg_play.drive_id
	and play.gsis_id = agg_play.gsis_id
	join game on game.gsis_id = agg_play.gsis_id
	where game.season_type = 'Regular'
		AND game.season_year IN (2009,2010,2011,2012,2013)
		AND play.down IN (1)
		AND agg_play.passing_att = 1
		AND agg_play.passing_incmp = 1
	)first
on first.gsis_id = second.gsis_id
and first.drive_id = second.drive_id
--and first.play_after = second.play_before
where second.play_id = first.play_after
group by second.team
order by "rush att after 1st and 10 inc pass" desc;

Thanks,
Robert

**Comment by BurntSushi** [comment]
I'd probably recommend grabbing all the plays for a particular drive and then use a programming language like Python to go the final mile. For example, while it's true that `play_id` doesn't correspond to an exact sequence, they should be in relative increasing order so that if you have a sequence of all plays for a particular drive, then you should be able to sort them by `play_id` which should give you a sequence that you can work with.

(You might consider doing this a game at a time instead of a drive at a time, to decrease the number of SQL roundtrips.)

**Comment by robertromeo5** [comment]
Awesome, thanks for the quick response.  It reminded me that I could use the rank() function in SQL to give the play_ids an exact sequence.  I got the query working and the stats I was looking for.

rank() over (partition by agg_play.gsis_id order by agg_play.play_id asc
