### ISSUE TITLE
2016 Preseason Game Results

### ISSUE THREAD

**Issue by artl603** [BurntSushi/nfldb#178]
Hi,  I ran an nfldb-update and don't see any of the recent pre-season games.  Has the DB been updated with these results?

Thanks

**Comment by p2j** [comment]
@artl603, this has been previously asked, and a solution is available, via [https://github.com/BurntSushi/nfldb/issues/161](https://github.com/BurntSushi/nfldb/issues/161) and [https://github.com/BurntSushi/nfldb/issues/170](https://github.com/BurntSushi/nfldb/issues/170)

You seem relatively new to Github, so let me offer some free advice; it's highly beneficial to search previously submitted issues before making your own, as in many cases what you want to ask has already been asked and discussed. Sometimes you have to search through issues that don't sound similar, but this is part of using and developing software with Github.

**Comment by BurntSushi** [comment]
Should be fixed.
