### ISSUE TITLE
could not get roster for team...

### ISSUE THREAD

**Issue by rjbks** [BurntSushi/nfldb#179]
It seems to have trouble for STL and JAX (`Could not get roster for team`) every time I attempt to run nfldb-update. I have set --player-interval 5, and ran that command a few times.

**Comment by rjbks** [comment]
should have posted this in nflgame. The fix is just changing the the team abbreviations in the nflgame module __init__.py teams list

from JAC to JAX and from STL to LA

**Comment by ochawkeye** [comment]
I question whether the fix of changing from `STL` to `LA` is best course of action.  Seems to me that years worth of historical data is lost without a team to map all of the old Rams games to.
