### ISSUE TITLE
Background Process on the Server

### ISSUE THREAD

**Issue by donlaur** [BurntSushi/nfldb#180]
Hello,
Again, I am not sure if I am asking this in the wrong place, I am asking on github under the Issues tab for nfldb.  Please redirect me if I am wrong asking here. 

I believe I have all of this working, I just need to figure out the queries more to get this correct.  The question I have is how to do put this working as a background process where it updates the Postgresql database under a good interval, and what is that interval, every 30 seconds, run nfldb-update?

Should I schedule this as a cron job during known game times?  I just want the stats to be updating every 30 seconds to so to the database.  I will be using the database for other things such as updating a page with an AJAX call that shows with some play by play of all active games.  Thanks.

**Comment by BurntSushi** [comment]
Just run `nfldb-update --interval 30` and it will run and update automatically. It's better than a cron job because it knows when to start updating and won't ping NFL.com when games aren't being played.

**Comment by donlaur** [comment]
Great, thank you, thinking it over I just want to update the database and
show how fantasy stats have changed over the last say, 5 minutes, instead
of a 30 second stream.  Doing this would be easier than running around
checking out every game update on many of the apps.  It might just be a
page full of active football players.  I plan on converting and showing
fanduel and draftkings scoring and also some season redraft yahoo.  PPR vs
half PPR.  I am loving this app and how it all works.

Very clever, just takes a bit for new people to get their heads around it.
Thanks again.
