### ISSUE TITLE
Commit for version 	0.2.16

### ISSUE THREAD

**Issue by patrick-praher** [BurntSushi/nfldb#183]
Hi,

I didn't debug into it, but i think you have a typo in the standard_team(team) method.

    team = team.lower()
    for teams in [teams1, teams2]:
        for variants in teams1:
            for variant in variants:
                if team == variant.lower():
                    return variants[0]
    return 'UNK'

I think line 3 should read "for variants in teams:" and not "..... teams1:" otherwise the line before that would be pointless.

Cheers,
Patrick

**Comment by patrick-praher** [comment]
Hi,

I did debug it now, and the L.A. Rams are not translated correctly as i expected.

Cheers,
Patrick

**Comment by weixiyen** [comment]
@BurntSushi the rams are not showing up as a result.  Could you update? Thanks!
