### ISSUE TITLE
Snap counts?

### ISSUE THREAD

**Issue by BYates123** [BurntSushi/nfldb#188]
This is great stuff, Andrew...well done. I was wondering if there is a way to calculate snap counts for players? After looking through each table in the db it doesn't seem like there is anything that keeps track of whether or not a player is on the field for a play, but I was hoping I was missing something.

**Comment by BurntSushi** [comment]
Nope. It's not in the source data.

**Comment by ochawkeye** [comment]
The play-by-play does not list all 22 players on the field for each play.

The NFL makes the data available after the fact in the GameBooks.
http://nflgsis.com/GameStatsLive/Schedule (u: media p: media)

**Comment by BYates123** [comment]
ah cool...thanks for the quick replies.
