### ISSUE TITLE
Player json is updating but the Player table in nfldb is not updating

### ISSUE THREAD

**Issue by wyattcurtis** [BurntSushi/nfldb#191]
I ran nfldb-update and could see Todd Gurley has LA as Team & RB as Position in the json file.
However, the player table shows UNK as Team & UNK as Position for Todd Gurley.

The player table only has 8 players where Team is LA

**Comment by BurntSushi** [comment]
Why did you close this? What did you do to fix it?

**Comment by wyattcurtis** [comment]
Apologies, this was not the item I intended to close

**Comment by BurntSushi** [comment]
What version of nfldb and nflgame do you have? (Run `pip list`.)

**Comment by wyattcurtis** [comment]
nfldb (0.2.10)
nflgame (1.2.20)

**Comment by BurntSushi** [comment]
Please upgrade `nfldb`. Your version is **over a year and a half old**.

**Comment by wyattcurtis** [comment]
I was able to resolve this by running:
nflgame-update-players
nfldb-update

BTW- nfldb updated as well, nfldb (0.2.17)
