### ISSUE TITLE
New Install Error: ConfigParser

### ISSUE THREAD

**Issue by jtroybaker** [BurntSushi/nfldb#193]
EDIT: Whoops, I posted this when my finger slipped while typing. Here's what I meant to say.

Hi! I'm installing nfldb for the first time and getting some errors. Sorry for not really being proficient in Python and thus having little idea what I'm doing.

Here is the traceback from trying to execute the recommended top 10 QBs test.

```
Traceback (most recent call last):
  File "top-ten-qbs.py", line 1, in <module>
    import nfldb
  File "C:\Anaconda3\lib\site-packages\nfldb\__init__.py", line 61, in <module>
    from nfldb.db import __pdoc__ as __db_pdoc__
  File "C:\Anaconda3\lib\site-packages\nfldb\db.py", line 2, in <module>
    import ConfigParser
ImportError: No module named 'ConfigParser'
```

I've tried using "pip install configparser" but installing the package/module/whatever isn't really clearing up the error.

Thanks for any advice!

**Comment by jtroybaker** [comment]
Sorry

**Comment by ochawkeye** [comment]
What version of Python are you using?  `nfldb` only works with Python 2.

I suspect you are attempting to use Python 3 (because of the `Anaconda3` in your path name and the fact that `ConfigParser` was renamed `configparser` in Python 3).

**Comment by jtroybaker** [comment]
Oh, that's simple enough. Thanks! Can you recommend a best practice for managing python versions? It seems like a good idea to have more than one.

**Comment by mlloyd5** [comment]
@jtroybaker 

See `virtualenv`
This has many helpful links
[](http://stackoverflow.com/questions/5844869/comprehensive-beginners-virtualenv-tutorial)
