### ISSUE TITLE
London Game times Wrong

### ISSUE THREAD

**Issue by joshutt** [BurntSushi/nfldb#209]
I've noticed that this has been a problem all season long where the London games have the flatly wrong time.  They aren't even close.

I've tried to update them directly in the database, but they are a weird utctime object instead of any of the standard postgres date/time types.  I'm guess that's some kind of custom datatype.  

Has anyone else solved this problem?

**Comment by BurntSushi** [comment]
> but they are a weird utctime object instead of any of the standard postgres date/time types

That's wrong. It is absolutely a standard datetime type. `utctime` just refers to a custom domain with a constraint that ensures time zone information is set properly. This is standard PostgreSQL practice. You can see the definition here: https://github.com/BurntSushi/nfldb/blob/master/nfldb/db.py#L452-L455

As for the actual problem, I believe some other folks have run into this too. See #202. It's not that surprising. We have to do some pretty hairy heuristics to figure out the right time, so it's not like this was easy to get right in the first place.
