### ISSUE TITLE
Calculate number of extra point attempts returned by the defense

### ISSUE THREAD

**Issue by BigWinston** [BurntSushi/nfldb#218]
Hi All,

Not an issue, but a question as I don't know where else to ask...

Q:  Is it possible to calculate the number of extra point attempts that are returned for a touchdown the opposite way by the defense?

Thanks!

**Comment by TomMcCabe** [comment]
Not sure how to do this w/ nflgame, but this works w/ SQL: 

    SELECT *
      FROM play
      where description like '%DEFENSIVE TWO-POINT ATTEMPT%' and description like '%ATTEMPT SUCCEEDS%'
    order by gsis_id

This gives you all extra point kicks and two point attempts that were returned for a defensive 2 pts. If you add `note = 'XPB'`, you'll get just the kicks, or `'2PPF'` for the two point attempts.

**Comment by BigWinston** [comment]
Thanks a bunch... I'll give it a try!
