### ISSUE TITLE
Using AWS

### ISSUE THREAD

**Issue by bhavik3jain** [BurntSushi/nfldb#220]
Is it possible to use AWS Postgresql for this database?

**Comment by BurntSushi** [comment]
Yes.

**Comment by BurntSushi** [comment]
If you'd like more help, then that's OK, but you'll need to *help us help you*. Please include more details about what you've tried, what you expected to happen and what actually happen. Please also include as much details about your setup/environment as possible.

**Comment by bhavik3jain** [comment]
The issue I am currently having is I have created an RDS instance on AWS and am connecting to it from DataGrip, but when I try to import the data into Postgres, it fails halfway through. Should I not be using DataGrip? Should I use pgAdmin instead?

**Comment by BurntSushi** [comment]
I don't know what DataGrip is. I'm sorry, but you're going to need to provide *a lot* more information. How does it fail? What output did you see? What commands did you run? What OS are you running `nfldb` on? How did you install it?

**Comment by BurntSushi** [comment]
@bhavik3jain Have you read the [installation instructions](https://github.com/BurntSushi/nfldb/wiki/Installation)? They should work with *any* PostgreSQL installation.

**Comment by bhavik3jain** [comment]
I am running this on a mac, do you suggest I should do this entirely through command line interface?

**Comment by BurntSushi** [comment]
Please follow the installation instructions. I can't help you otherwise because you're not giving enough details. Sorry.

**Comment by seanlhiggins** [comment]
@bhavik3jain This is what you want - http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/PostgreSQL.Procedural.Importing.html
Through your Terminal/Command Line use the command:
psql \
   -f mydb2dump.sql \
   --host mypginstance.c6c8mntzhgv0.us-west-2.rds.amazonaws.com \
   --port 8199 \
   --username myawsuser \
   --password password \
   --dbname mydb2 

Thanks for the awesome resources, @BurntSushi I love this stuff.

**Comment by bhavik3jain** [comment]
Yes this is exactly what I needed. Thanks so much
