### ISSUE TITLE
Library with version 7 is older than the schema with version 8

### ISSUE THREAD

**Issue by jeudycecropia** [BurntSushi/nfldb#222]
Hi,

I moved from an AWS box to a different server using ubuntu where I just installed postgres following the [documentation](https://github.com/BurntSushi/nfldb/wiki/Installation-on-Ubuntu) but when I try to run the test script, I get this error:

> AssertionError: Library with version 7 is older than the schema with version 8

on this line:

`db = nfldb.connect()`

I imported the [given database ](http://burntsushi.net/stuff/nfldb/nfldb.sql.zip).

What else can I check?

Thanks

**Comment by ochawkeye** [comment]
[`nfldb.connect()`](https://github.com/BurntSushi/nfldb/blob/9cc2fe8280cada7c1595d54e4dc698b99da72a40/nfldb/db.py#L102-L109) is purposely making sure the API version and database schema version are the same.

What version of `nfldb` are you using?  The API version in the current `nfldb` release _is_ version 8 [here](https://github.com/BurntSushi/nfldb/blob/master/nfldb/db.py#L20).

**Comment by jeudycecropia** [comment]
You are absolutely right. Upgrading to the latest version fixed it. Thanks!
