### ISSUE TITLE
Execute a psql script within a Python script

### ISSUE THREAD

**Issue by mrg1999** [BurntSushi/nfldb#227]
I would like to Insert JAX into the 'team' table inside the  nfldb-update script
i.e. 
`psql -U nfldb -f C:\Python27\Insert_JAX.sql`
where Insert_JAX.sql is
`INSERT into team values('JAX','Jacksonville', 'Jaguars')`
Is this possible? And could someone help me with the correct syntax to do this?

**Comment by mrg1999** [comment]
It seems I'm on the right track, this code seems to be working:
```
import psycopg2
try:
    conn = psycopg2.connect("dbname='nfldb' user='nfldb' host='localhost' password='passwd'")
except:
    print "I am unable to connect to the database"
cur = conn.cursor()
try:
    cur.execute("""INSERT into team values('JAX','Jacksonville', 'Jaguars') """)
except:
    print "INSERT failed"
```

**Comment by andr3w321** [comment]
Yep that should work.  Remember to close the cursor and connection when you're done with 

```
cur.close()
conn.close()
```

I would also recommend moving the password into a `.pgpass` file(google it for configuration) for easier access and more security so you don't litter your scripts with your db pass.  Your connection string will then become `conn = psycopg2.connect("host=localhost dbname=nfldb user=nfldb")`  You can query with 

```
week = 5
cur.execute("""SELECT * FROM game WHERE week = %s LIMIT 5;""",(week,))
print cur.fetchall()
```

**Comment by mrg1999** [comment]
I've edited the .update script in site-packages\nfldb to include lines to: 
INSERT JAC into the team Table,
UPDATE JAX to JAC
DELETE JAX from the team Table
For me this serves two purposes:
1. It eliminates the need to execute three different scripts (INSERT JAC, UPDATE nfldb & UPDATE/DELETE JAX)
2. It simplifies running nfldb-update with an interval set - I just need to send an interrupt to stop the update when I'm done.

```
……………………………………………………………………………………………………………………………………………………..
      if interval is None:
            # Simulation implies a repeated update at some interval.
            interval = 10
            log('--interval not set, so using default simulation '
                'interval of %d seconds.' % interval)
    ########## BEGINNING OF EDIT
    import psycopg2
    #try:
        #conn = psycopg2.connect("dbname='nfldb' user='nfldb' host='localhost'")
    #except:
        #log('Unable to connect to nfldb')
    #cur = conn.cursor()
    def doit():
        try:
            conn = psycopg2.connect("dbname='nfldb' user='nfldb' host='localhost'")
        except:
            log('Unable to connect to nfldb')
        log('Insert JAX')
        ########## INSERT JAX INTO team TABLE
        cur = conn.cursor()
        try:
            cur.execute("""INSERT into team values('JAX','Jacksonville', 'Jaguars') """)
        except:
            log('INSERT failed')
        log('-' * 79)
        log('STARTING NFLDB UPDATE AT %s' % now())
        log('Connecting to nfldb... ', end='')
        db = nfldb.connect()
        log('done.')
       ……………………………………………………………………………………………………………………………………………………..
        # Now update games.
            update_games(db, batch_size=batch_size)

        log('Closing database connection... ', end='')
        db.close()
        log('done.')
        log('FINISHED NFLDB UPDATE AT %s' % now())
        log('-' * 79)
        ############ UPDATE JAX TO JAC
        log('Delete JAX')
        try:
            cur.execute("""UPDATE play SET pos_team = 'JAC' WHERE pos_team ='JAX';""")
        except:
            log('UPDATE failed')
        ##########  DELETE JAX FROM team TABLE
        try:
            cur.execute("""DELETE FROM team WHERE team_id ='JAX';""")
        except:
            log('DELETE failed')


    if interval is None:
        doit()
    else:
        if interval < 15 and simulate is None:
            log('WARNING: Interval %d is shorter than 15 seconds and is '
                'probably wasteful.\nAre you sure you know what you are doing?'
                % interval)
        while True:
            done = doit()
            if done:
                sys.exit(0)
            time.sleep(interval)
```

**Comment by mrg1999** [comment]
My program (written in VBA) has an option titled "Schedules" which allows the selection of any week during the season.
Selecting a game week in the future will display the teams, day and time of each game that week.
Selecting a game week in the past will display the same information plus the final scores.
Selecting the current week will display the same information depending on whether the game hasn't started or is finished...if the game is in progress, the scores, yard line & down, and play descriptions are updated dynamically.
Under the first two scenarios the 'Schedules' macro executes `nfldb-update `one time (at the beginning of the script)
If the current week is selected AND there are games in progress `nfldb-update `is executed with `--interval 30 `argument
I need the proper syntax to send an interrupt (CNTRL C) to `nfldb-update `when the 'interval' argument is set.

**Comment by mrg1999** [comment]
I was experimenting with killing the python.exe. PID and now I'm getting an error when running the nfldb-update script.
```
c:\Python27\Scripts>python nfldb-update
Traceback (most recent call last):
  File "nfldb-update", line 5, in <module>
    import nfldb.update
  File "C:\Python27\lib\site-packages\nfldb\update.py", line 14, in <module>
    import nflgame
  File "C:\Python27\lib\site-packages\nflgame\__init__.py", line 97, in <module>
    import nflgame.game  # noqa
  File "C:\Python27\lib\site-packages\nflgame\game.py", line 12, in <module>
    import nflgame.sched
  File "C:\Python27\lib\site-packages\nflgame\sched.py", line 47, in <module>
    games, last_updated = _create_schedule()
  File "C:\Python27\lib\site-packages\nflgame\sched.py", line 26, in _create_schedule
    data = json.loads(open(jsonf).read())
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 43322 column 13 (char 696317
```)

**Comment by mrg1999** [comment]
I had to re-load the entire python folder from a copy I had saved on a thumb drive to get the `nfldb-update `script to work again.
 I was able to successfully add the JAX/JAC enter, replace and delete scripts to the `nfldb-update `script (as shown above) - while this may not be necessary next year, we may encounter the same problem with the Raiders move so it will be easily modified if need be.
As I previously stated, I need to run `nfldb-update `while passing the `--interval 15 `argument for games that are in progress.
`import subprocess as sp`
`extProc = sp.Popen(['python', 'C:/Python27/Scripts/nfldb-update', '--interval', '15'])`
I need to terminate the `nfldb-update `script when the 'Schedule' option is exited (via a clicked button on the VBA page) and this seems to be where the problem is...I can run the kill script say 10 times with no problem but suddenly the `nfldb-update `script becomes corrupted (as shown above). It seems to be that if the timing of the kill signal is just right, it corrupts the program.
```
import subprocess as sp
extProc = sp.Popen(['python', 'C:/Python27/Scripts/nfldb-update', '--interval', '15']) 
When I exit the 'Schedule' script (in VBA), I need a way to terminate the nfldb-update script which is running every 15 seconds. 
import os
import subprocess
import signal
import psutil
kpid = None
PIDno=os.getpid() ##PIDno = This PID (not the one we want to kill)
PROCNAME = "python.exe"

def kill_proc_tree(pid, including_parent=True):    
    parent = psutil.Process(pid)
    children = parent.children(recursive=True)
    for child in children:
        child.kill()
    psutil.wait_procs(children, timeout=5)
    if including_parent:
        parent.kill()
        parent.wait(5)

for proc in psutil.process_iter():
    if proc.name() == PROCNAME:
	if str(PIDno) not in str(proc): ##Find the PID we want to kill
            kpid = proc.pid
               
if kpid != None:
    kill_proc_tree(kpid)    
else:
    print('PID not found') 
```
I'd really appreciate it if someone can help me with this problem!

**Comment by mrg1999** [comment]
Solution!
If the _Schedules_ option is selected on my main menu, a screen is displayed showing each game, time, day of week, scores etc for the selected week.
Two buttons _Print_ and _Return_ are also displayed (Print - prints the displayed table, Return - returns to the main menu)
If the current week is selected and there are any games in progress a third button _Refresh_ is displayed. Clicking this button starts `nfldb-update --interval 15`
It also creates a dummy file in the `Python27\temp folder `named `interval.csv`
When the _Return_ button is clicked, the program exits the Schedules routine and deletes the dummy file.

I modified the `update.py `script to monitor the existence of the dummy file during the interval loop and if the file no longer exists, the script exists gracefully with
`sys.exit(0)`

update.py mod:

```
#!/usr/bin/env python2.7
         ...
import os.path
        ...
 if interval is None:
     doit()
else:
    if interval < 15 and simulate is None:
        log('WARNING: Interval %d is shorter than 15 seconds and is '
        'probably wasteful.\nAre you sure you know what you are doing?'
        % interval)
    while True:
        done = doit()
        if done:
            sys.exit(0)
        if not os.path.exists("C:/Python27/temp/interval.csv"):     ## If 'interval.csv doesn't exist, exit program      
            sys.exit(0)
        time.sleep(interval)
```

**Comment by mrg1999** [comment]
@andr3w321 
`update.py `seems to be closing the cursor and connection on its own. I get an error that they are already closed so I left it out.
My authentication method is set to trust in the `pg_hba.conf `file so no password is needed.
Currently my program downloads the stats of every game in progress every 10 seconds but I think a more efficient way would be to monitor 'some_file' for a change in the modified time, indicating a change in a game in progress (score, down, end of quarter, etc.)
Just not sure which file would be the best one to monitor.
