### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by mhberro** [BurntSushi/nfldb#229]
Hi, I'm currently using version 0.2.17 of nfldb and when attempting one of the examples I hit the following error:

"AttributeError: 'function' object has no attribute 'get_transaction_status'"

I've tried searching Wiki for a related issue but haven't been successful in extracting anything relevant to my issue. Has anyone encountered this error before? Any help would be much appreciated! Below is the exact steps I executed to get to this point:

>>> import nfldb
>>> db=nfldb.connect
>>> q = nfldb.Query(db)
>>> q.game(season_year=2013, season_type='Preseason', team ='NE')
<nfldb.query.Query object at 0x03BE0AB0>
>>> for g in q.as_games():
	print g

Traceback (most recent call last):
  File "<pyshell#6>", line 1, in <module>
    for g in q.as_games():
  File "C:\Python27\lib\site-packages\nfldb\query.py", line 792, in as_games
    with Tx(self._db, factory=tuple_cursor) as cursor:
  File "C:\Python27\lib\site-packages\nfldb\db.py", line 281, in __init__
    tstatus = psycho_conn.get_transaction_status()
AttributeError: 'function' object has no attribute 'get_transaction_status'

**Comment by mrg1999** [comment]
change
`db=nfldb.connect`
to 
`db=nfldb.connect()`

**Comment by mhberro** [comment]
Thanks for the quick response! I don't know how I glossed over that detail.
