### ISSUE TITLE
Use with MongoDB instead

### ISSUE THREAD

**Issue by mginz83** [BurntSushi/nfldb#239]
Would it be possible to use mongodb instead? And if so what steps would we take to link those up?

**Comment by BurntSushi** [comment]
No. This library is tightly coupled to a relational database schema. Why can't you use postgresql?

If you desperately want mongodb, then you need to go back to nflgame and build it out yourself.

**Comment by mginz83** [comment]
Thanks for the quick response. The application I'm building for IOS and Android is using mongodb. It would be nice to keep everything all in the same place.

**Comment by BurntSushi** [comment]
You will have to choose between building your own version of nfldb or using postgresql. Good luck.
