### ISSUE TITLE
Installing NFLDB with homebrew

### ISSUE THREAD

**Issue by Arrashg** [BurntSushi/nfldb#244]
Hey all!

Having trouble with the original installation instructions. When I switch to root and type in the command, it says command not found. I am using homebrew and am relatively new with postgresql and even with using the command line. Any help is much appreciated. I attached an image to demonstrate.

Thanks
<img width="401" alt="screen shot 2017-07-31 at 9 41 40 pm" src="https://user-images.githubusercontent.com/20796673/28809609-39ec6874-7639-11e7-99c1-1cee29dc2e66.png">

**Comment by BurntSushi** [comment]
@Arrashg The wiki links to a page that describes how to install PostgreSQL on a mac. Otherwise, you're on your own I'm afraid since I'm not a Mac user. Following instructions that are written for Linux with a Mac will inevitably end in sadness.
