### ISSUE TITLE
Password Authentication Error

### ISSUE THREAD

**Issue by mcampb05** [BurntSushi/nfldb#245]
Please help. I have followed the directions closely but am coming up with this error

C:\Users\Matthew Campbell\Desktop> python ten-qbs.py
Traceback (most recent call last):
  File "ten-qbs.py", line 3, in <module>
    db = nfldb.connect()
  File "C:\Python27\lib\site-packages\nfldb\db.py", line 126, in connect
    host=host, port=port)
  File "C:\Python27\lib\site-packages\psycopg2\__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "nfldb"

**Comment by BurntSushi** [comment]
There's not much we can do to help you. The error message says exactly what the problem is. You'll need to figure out how to fix your login details with PostgreSQL. The wiki installation instructions walk you through the PostgreSQL setup.

**Comment by mcampb05** [comment]
Do you think uninstalling PostgreSQL and reinstalling is the best bet. I cant figure out how to change password
