### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by mcampb05** [BurntSushi/nfldb#246]
Help. No matter what I do I cant get this to install. Can anyone help me? 

The errors I keep getting at around running the top-ten-qbs and nfldb update scripts

If you run into any kind of trouble while trying to get nfldb installed, please open a new issue on nfldb's issue tracker. If you're thinking, "I'm not sure if this belongs on an issue tracker..." then my answer to you is: "Yes it does! Post it!" Not only does it help me stay organized, but it benefits others that come after you who run into similar problems

**Comment by ochawkeye** [comment]
Need some details.

**Comment by mcampb05** [comment]
I think I would have to share screen. A lot of this is new to me and I have run through the windows install instructions many times. Cant seem to get to work.

**Comment by mcampb05** [comment]
C:\Python27\Scripts> "C:\Users\Matthew Campbell\Desktop\Python Scripts NFLDB\top-ten-qbs.py"

When I run this it just pops open the txt file

**Comment by ochawkeye** [comment]
Because you don't have `.py` files associated with Python on your PC.

Try running `python "C:\Users\Matthew Campbell\Desktop\Python Scripts NFLDB\top-ten-qbs.py"`

**Comment by mcampb05** [comment]
C:\Users\Matthew Campbell\Desktop\Python Scripts NFLDB>python "C:\Users\Matthew Campbell\Desktop\Python Scripts NFLDB\top-ten-qbs.py"
Traceback (most recent call last):
  File "C:\Users\Matthew Campbell\Desktop\Python Scripts NFLDB\top-ten-qbs.py", line 3, in <module>
    db = nfldb.connect()
  File "C:\Python27\lib\site-packages\nfldb\db.py", line 140, in connect
    set_timezone(conn, timezone)
  File "C:\Python27\lib\site-packages\nfldb\db.py", line 182, in set_timezone
    c.execute('SET timezone = %s', (timezone,))
  File "C:\Python27\lib\site-packages\psycopg2\extras.py", line 249, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.DataError: invalid value for parameter "TimeZone": "US/Pacific
The name of the PostgreSQL database containing NFL data."

**Comment by mcampb05** [comment]
Looks like maybe an issue with timezone parameter?

**Comment by ochawkeye** [comment]
What does your `config.ini` look like (from step 12 in the [Windows install instructions](https://github.com/BurntSushi/nfldb/wiki/Windows-Install)?  On my machine this is located in `D:\Python27\share\nfldb\config.ini`

I'm `US/Central`, but I do notice in the samples that both `US/Pacific` and `US/Pacific-New` are options.

**Comment by mcampb05** [comment]
I tried both of those. Heres what mine currently looks like

[pgsql]
# The time zone to use in the PostgreSQL session by default.
# You can see a list of available time zone names with the following query:
# 
#     select * from pg_timezone_names
#
# Here are some common ones:
#
#    US/Alaska
#    US/Samoa
#    US/Hawaii
#    US/Mountain
#    US/Indiana-Starke
#    US/Pacific
#    US/Central
#    US/Michigan
#    US/Aleutian
#    US/East-Indiana
#    US/Arizona
#    US/Eastern
#    US/Pacific-New
#
# Datetimes are always stored as UTC, but this time zone setting
# can be used to change how datetimes are returned in SELECT queries.
timezone = US/Pacific-New

 The name of the PostgreSQL database containing NFL data.
database = nfldb

# The username and password for the database specified above.
# The user should have permission to add, delete and remove data.
# Also, the user should have permission to create/alter/drop tables,
# indexes and types.
user = nfldb
password = Hurley25

# The host of the PostgreSQL server. When using a local database, this should
# be set to "localhost".
host = localhost

# The port that the PostgreSQL server is running on. It is set to the
# default port of 5432.
port = 5432

**Comment by mcampb05** [comment]
[pgsql]
# The time zone to use in the PostgreSQL session by default.
# You can see a list of available time zone names with the following query:
# 
#     select * from pg_timezone_names
#
# Here are some common ones:
#
#    US/Alaska
#    US/Samoa
#    US/Hawaii
#    US/Mountain
#    US/Indiana-Starke
#    US/Pacific
#    US/Central
#    US/Michigan
#    US/Aleutian
#    US/East-Indiana
#    US/Arizona
#    US/Eastern
#    US/Pacific-New
#
# Datetimes are always stored as UTC, but this time zone setting
# can be used to change how datetimes are returned in SELECT queries.
timezone = US/Pacific-New

 The name of the PostgreSQL database containing NFL data.
database = nfldb

# The username and password for the database specified above.
# The user should have permission to add, delete and remove data.
# Also, the user should have permission to create/alter/drop tables,
# indexes and types.
user = nfldb
password = xxxx

# The host of the PostgreSQL server. When using a local database, this should
# be set to "localhost".
host = localhost

# The port that the PostgreSQL server is running on. It is set to the
# default port of 5432.
port = 5432

**Comment by mcampb05** [comment]
I changed password to xxxx but I have the nfldb password I set up in there

**Comment by ochawkeye** [comment]
Did you happen to remove the `#` sign from the next line in that file by any chance?
```
timezone = US/Central

# The name of the PostgreSQL database containing NFL data.
database = nfldb
```

**Comment by mcampb05** [comment]
Possibly. Let me try that

**Comment by ochawkeye** [comment]
By the way, when copying & pasting code, if you "fence" the block between three tick marks ( ` : `SHIFT+~`) it will be much more readable on github.

**Comment by mcampb05** [comment]
Good to know! I appreciate it! I am a rookie. One last question well I have you being so generous to help out. What's the best way to learn how to write different queries? I see I can somewhat follow the syntax in the top-ten qbs scrips but I am not really sure what I am doing.

Much appreciate the assistance!

**Comment by mcampb05** [comment]
testing
'''
[pgsql]
# The time zone to use in the PostgreSQL session by default.
# You can see a list of available time zone names with the following query:
# 
#     select * from pg_timezone_names
#
# Here are some common ones:
#
#    US/Alaska
#    US/Samoa
#    US/Hawaii
#    US/Mountain
#    US/Indiana-Starke
#    US/Pacific
#    US/Central
#    US/Michigan
#    US/Aleutian
#    US/East-Indiana
#    US/Arizona
#    US/Eastern
#    US/Pacific-New
#
# Datetimes are always stored as UTC, but this time zone setting
# can be used to change how datetimes are returned in SELECT queries.
timezone = US/Pacific

#The name of the PostgreSQL database containing NFL data.
database = nfldb

# The username and password for the database specified above.
# The user should have permission to add, delete and remove data.
# Also, the user should have permission to create/alter/drop tables,
# indexes and types.
user = nfldb
password = xxx

# The host of the PostgreSQL server. When using a local database, this should
# be set to "localhost".
host = localhost

# The port that the PostgreSQL server is running on. It is set to the
# default port of 5432.
port = 5432

'''

**Comment by mcampb05** [comment]
the # was the problem!

**Comment by ochawkeye** [comment]
The wiki has a ton of examples [here](https://github.com/BurntSushi/nfldb/wiki/An-introduction-to-the-query-interface), [here](https://github.com/BurntSushi/nfldb/wiki/Disjunctive-criteria), [here](https://github.com/BurntSushi/nfldb/wiki/Aggregate-searching), and [here](https://github.com/BurntSushi/nfldb/wiki/More-examples).

If there's something in particular you're looking for, I would try running a search on this issue tracker with some keywords.  If that still fails don't hesitate to ask and someone will most likely be able to assist.

FYI - you are using apostrophes ' and not a tick marks \`

**Comment by mcampb05** [comment]
Think I fixed it. Thanks again for all your help

**Comment by MalnourishedNigerianChild** [comment]
I don't know how to like make an issue on this but I really need help on something so can someone please help me

**Comment by ochawkeye** [comment]
Yep
