### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by mcampb05** [BurntSushi/nfldb#248]
Newb question. How would i export play data to a csv after writing a query? This table is huge so I am having trouble connecting to it with third party apps like power query. Think i need to drill it down a bit.
Any help is appreciated

**Comment by BurntSushi** [comment]
Take whatever data you want to export it and write it to a file using Python's standard library [`csv`](https://docs.python.org/2.7/library/csv.html#module-csv) module.

If you want more help, please provide more details, such as the code you've written. Please tell us what you've tried and how it didn't work.
