### ISSUE TITLE
Depth Chart

### ISSUE THREAD

**Issue by illegalnumbers** [BurntSushi/nfldb#249]
Is there a way to get the depth chart for each team at each position?

**Comment by donlaur** [comment]
Ourlads.com.  Not really part of this application though. I don't think it
is possible on this app.

**Comment by illegalnumbers** [comment]
Hm could I open a ps to do that then? It seems like an easy enough scraping job. Be good functionality to have on hand. I know knowing the depth chart is very helpful for draft decisions.

**Comment by illegalnumbers** [comment]
could join teams + players and give an extra column called depth or something.

**Comment by ochawkeye** [comment]
I'm not @BurntSushi and I'd never presume to speak for him, but this strikes me as a bit of scope creep.  

Don't get me wrong, I can see some of the uses you have in mind and the benefits that what you're talking about would provide.  But where will you get all of the historical depth charts to align with the historical play-by-play data that `nfldb` is handling at its core?

A snap shot of today's depth chart would be trivial to include.  But how does knowing who the Panther's #2 wide receiver at this moment help you when it comes to analyzing a game that was played in 2012 or in week 3 of 2016 or even last week?

Currently with `nfldb` it's not a simple task to learn that Marshawn Lynch played for Seattle in 2015.  Even more difficult to find that he played for Buffalo in 2009.  And next to impossible to figure out that he played for Buffalo in week 4 2010 and Seattle in week 5 2011.

```python
import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2015, season_type='Regular')
q.player(full_name="Marshawn Lynch")
print q.as_players()[0]
```
```
Marshawn Lynch (OAK, RB)
```

Tracking the depth chart for every position on all 32 teams for each week of the season sounds like a project all unto itself.

**Comment by illegalnumbers** [comment]
Very good point. I don't think the project would be that difficult but I can see the scope creep here. I'd like to have the owner weigh in though.

**Comment by BurntSushi** [comment]
@ochawkeye is right. Adding any kind of scraping is *never* simple. It is easy enough to produce a one time hack that serves a specific use case, but it is another to develop it into something that is generally useful and is maintainable. There is quite a lot of work put into the existing scraping for generic player meta data, and specific logic in place to do efficient updates of that data.

If I were more ambitious and had more time to devote to this project, them this might be something i would consider doing, but adding more maintenance burden at this point is a non-starter.
