### ISSUE TITLE
Players table?

### ISSUE THREAD

**Issue by psuanm5030** [BurntSushi/nfldb#250]
Now that we have the 2017 pre-season kicked off, i was updating the data.  One thing I noticed is that there is still a lot of missing information - particularly for rookies.  E.g., Mitchell Trubisky for the bears was 18/25 the other night in his first game, however the player table is still showing null for a lot of his key attributes, including position, team and name among many other things.  However the play detail is there.  I suspect that I errrored at some point and gsis information was pulled but never mapped to actual metadata, therefore leaving certain players with inconsistent mapping.  I also noticed that I have Leonard Fournette's metadata (fullname, college, position) but his gsis_name is incomplete.

Am I missing something or are others seeing this too?

**Comment by BurntSushi** [comment]
Player meta data for rookies often doesn't become available until close to the season start. This happens every year. Search the issue tracker for more details. (You might want to search the nflgame repo too.)
