### ISSUE TITLE
Blank Columns

### ISSUE THREAD

**Issue by mcampb05** [BurntSushi/nfldb#253]
Hello - This maybe another newb issue bit when loading data there several columns that appear blanl

1.Public Drive; Start field, Start time, end filed, end time
2.Public Play; Yardline

Hoping someone can assist.

Thanks

**Comment by ochawkeye** [comment]
Without some code it's tough to know what you're referring to here.
Can you show the description of a particular drive or play that demonstrates these fields being blank?

```python
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2017, week=2, season_type='Preseason', team='BUF')

for drive in q.limit(3).as_drives():
    print drive
    print drive.start_field, drive.start_time
    print drive.end_field, drive.end_time
print '-'*25
for play in q.limit(3).as_plays():
    print play
    print play.yardline
```
```
[Interception] BUF from OWN 23 to OPP 8  (lasted 03:00 - Q4 03:00 to Q4 00:00)
OWN 23 Q4 03:00
OPP 8 Q4 00:00
[Touchdown   ] PHI from OWN 40 to OPP 1  (lasted 01:57 - Q4 04:57 to Q4 03:00)
OWN 40 Q4 04:57
OPP 1 Q4 03:00
[Touchdown   ] BUF from OPP 9  to OPP 9  (lasted 00:25 - Q4 05:22 to Q4 04:57)
OPP 9 Q4 05:22
OPP 9 Q4 04:57
-------------------------
(BUF, OWN 35, Q1) S.Hauschka kicks 65 yards from BUF 35 to end zone, Touchback.
OWN 35
(PHI, OWN 25, Q1, 1 and 10) (15:00) L.Blount left end to PHI 23 for -2 yards (J.Poyer).
OWN 25
(PHI, OWN 23, Q1, 2 and 12) (14:22) C.Wentz pass incomplete short left to A.Jeffery.
OWN 23
```

**Comment by mcampb05** [comment]
Im using tableau so im not 100% sure either. All of the data is blank when import the tables for those columns. Thought someone might know and it's a simple solution.

**Comment by ochawkeye** [comment]
Are you querying a game that has not started yet that does not yet have any drives or plays?

**Comment by mcampb05** [comment]
Pulled in the entire table and appears to be blank. Sounds like this is an issue on my end since it is working fine through python query. Thanks for your help :)
