### ISSUE TITLE
Missing data from week 1 of preseason 2017

### ISSUE THREAD

**Issue by daugaard** [BurntSushi/nfldb#254]
After installing nfldb and updating this week I see all the data from the last years (2009 through 2016) as well as data from this current week of preseason (week 2), I do however not see data from the first week of preseason this year or a scheduled games for the rest of this season. 

Is this because nflgame has not been updated with the current season yet? 
And if so are there any plans to update nflgame with the current season, or are there any instructions on how to do it then I would be happy to help out.

**Comment by rptaheri** [comment]
Try running the schedule update script and re-running your update script.

**Comment by daugaard** [comment]
I did that still nothing. Are you seeing the complete schedule for the 2017 season?

**Comment by rptaheri** [comment]
What command did you execute? You need to run update_sched.py --year 2017 and that worked for me. You'll probably need to insert LAC to your database manually. If you can't figure that out, search for issues where people had problems with JAX and JAC and you'll figure it out.

**Comment by daugaard** [comment]
That totally did the trick. Thanks so much for your help :+1: :)
