### ISSUE TITLE
Syntax Error in query.py

### ISSUE THREAD

**Issue by bstrain71** [BurntSushi/nfldb#257]
def guess_position(pps):
    """
    Given a list of `nfldb.PlayPlayer` objects for the same player,
    guess the position of the player based on the statistics recorded.

    Note that this only distinguishes the offensive positions of QB,
    RB, WR, P and K. If defensive stats are detected, then the position
    returned defaults to LB.

    The algorithm used is simple majority vote. Whichever position is
    the most common is returned (and this may be `UNK`).
    """
    if len(pps) == 0:
        return types.Enums.player_pos.UNK

    counts = defaultdict(int)
    for pp in pps:
        counts[pp.guess_position] += 1
    return max(counts.items(), key=lambda (_, count): count)[0] ## This line [213] throws me the following error:

![image](https://user-images.githubusercontent.com/20056207/29845294-c98da5f4-8d01-11e7-85a9-f937347a65b8.png)

What am I doing wrong? I have reset my environment, reinstalled the package, etc...Have tried running in both Python 2 and Python 3 environments.

**Comment by ochawkeye** [comment]
Can we see *your* code in tmpjhid5s.py?

Here's some code for how that method works.  On a play-by-play basis, it's less accurate that when tried over a group of plays.

```python
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2017, week=3, season_type='Preseason', team='MIN')

plays = q.as_plays()
for play in plays[-5:]:
    print play
    for pp in play.play_players:
        print '\t', pp.player, pp
        print '\t\tGuessed position: {} / Real position: {}'.format(
            pp.guess_position, pp.player.position)
    print '-'*25
```
```
(MIN, OPP 5, Q4, 1 and 5) (:10) (Shotgun) T.Heinicke pass incomplete short left to I.Fruechte (A.Jackson).
    Asa Jackson (SF, DB) {'defense_pass_def': 1}
        Guessed position: LB / Real position: DB
    Isaac Fruechte (MIN, WR) {'receiving_tar': 1}
        Guessed position: WR / Real position: WR
    Taylor Heinicke (MIN, QB) {'passing_incmp_air_yds': 5, 'passing_att': 1, 'passing_incmp': 1}
        Guessed position: QB / Real position: QB
-------------------------
(MIN, OPP 5, Q4, 2 and 5) (:05) (Shotgun) T.Heinicke pass incomplete short right to S.Coley (K.Reaser). PENALTY on SF-K.Reaser, Defensive Pass Interference, 4 yards, enforced at SF 5 - No Play.
    Keith Reaser (SF, CB) {}
        Guessed position: UNK / Real position: CB
-------------------------
(MIN, OPP 1, Q4, 1 and 1) (:01) (Shotgun) T.Newby up the middle for 1 yard, TOUCHDOWN.
    Terrell Newby (MIN, RB) {'rushing_att': 1, 'rushing_tds': 1, 'rushing_yds': 1}
        Guessed position: RB / Real position: RB
-------------------------
(UNK, N/A, Q4) Timeout #2 by SF at 00:00.
-------------------------
(MIN, OPP 2, Q4) (Pass formation) TWO-POINT CONVERSION ATTEMPT. T.Heinicke rushes right end. ATTEMPT SUCCEEDS.
    Taylor Heinicke (MIN, QB) {'rushing_twopta': 1, 'rushing_twoptm': 1}
        Guessed position: UNK / Real position: QB
```

**Comment by BurntSushi** [comment]
The error you reported is indicative of you using Python 3. As the README
states, this only works with Python 2.

**Comment by bstrain71** [comment]
I think I'm running it in Python 2 but I'm not naive enough to think that I am right and everyone else is wrong...

It must be an issue with my environment. Will continue to troubleshoot!

Thanks for the feedback.

**Comment by bstrain71** [comment]
Wrong environment.
