### ISSUE TITLE
2017 rookie names not correct? "K.Golladay" v. "Kenny Golladay"

### ISSUE THREAD

**Issue by kennysushi** [BurntSushi/nfldb#263]
I ran the nflgame-update-players and I saw that it was having trouble with all the 2017 rookies:

> Could not get profile URL for (00-0033932, K.Golladay)
> -------------------------------------------------------------------------------
> Could not get profile URL for (00-0033283, T.Bowser)
> -------------------------------------------------------------------------------
> Could not get profile URL for (00-0033280, C.McCaffrey)

I see this is reflected in the week 1 stats where the names are listed as "First Name Abrev.Last Name" ie like K.Golladay, whereas all other players have their full first and last names. It seems then also the player data is returning as UNK,UNK for these rookies.

>              Player  Tar  Rec  RuAtt  RecYds  RuYds  OffYds  PaAtt  \
>145  K.Golladay (UNK, UNK)  7.0  4.0    0.0    69.0    0.0    69.0    0.0   

Simply re-running nflgame-update-players doesn't seem to fix this issue. I wonder if this will self correct after this week? Or has anyone else found a similar issue or work around?

**Comment by ochawkeye** [comment]
I'm not seeing this issue with my install.

```python
import nflgame
games = nflgame.games(2017, 1, 'CAR', 'CAR', 'REG')
plays = nflgame.combine_max_stats(games)

christian_mccaffrey = nflgame.find('Christian McCaffrey')[0]

print christian_mccaffrey
print plays.playerid(christian_mccaffrey.playerid).formatted_stats()
```

```
Christian McCaffrey (RB, CAR)
fumbles_tot: 1, puntret_yds: 7, fumbles_lost: 1, receiving_yac_yds: 37, puntret_tot: 3, fumbles_forced: 1, receiving_rec: 5, rushing_yds: 45, puntret_fair: 1, receiving_yds: 38, rushing_att: 13, receiving_tar: 7, receiving_tds: 0, fumbles_rcv: 0, receiving_lngtd: 0, puntret_ret: 3, puntret_avg: 2, rushing_tds: 0, rushing_twopta: 0, receiving_twopta: 0, receiving_twoptm: 0, rushing_twoptm: 0, puntret_lngtd: 0, rushing_lngtd: 0, fumbles_yds: 0, receiving_lng: 16, puntret_lng: 4, puntret_tds: 0, fumbles_trcv: 0, rushing_lng: 11
```

**Comment by ochawkeye** [comment]
Sorry, didn't realize I was posting to `nfldb` issues.  Same answer, just different code:

```python
import nfldb
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2017, week=1, team='CAR', season_type='Regular')
q.player(full_name='Christian McCaffrey')

for player in q.as_aggregate():
    print player.player, player
```
```
Christian McCaffrey (CAR, RB) {'fumbles_tot': 1L, 'fumbles_forced': 1L, 'rushing_att': 13L, 'puntret_fair': 1L, 'fumbles_lost': 1L, 'receiving_yac_yds': 37L, 'receiving_rec': 5L, 'rushing_yds': 45L, 'puntret_tot': 3L, 'receiving_yds': 38L, 'puntret_yds': 7L, 'receiving_tar': 7L}
```

**Comment by kennysushi** [comment]
Thanks for the reply, as I was suspecting, this fixed itself without any further intervention. Possibly just I need the ~12 hours after games played to update nfldb/nflgame.
