### ISSUE TITLE
nfl-update week 1 issue

### ISSUE THREAD

**Issue by ryandonn427** [BurntSushi/nfldb#270]
I updated the database as normal but for some reason week 1 of the 2017 Regular season isn't appearing. 
This seems weird as week 2 has already appeared.

**Comment by ochawkeye** [comment]
Potentially same problem as https://github.com/BurntSushi/nflgame/issues/331?

Give that a try.

**Comment by ryandonn427** [comment]
Thanks! I must have missed that post when I was searching.
