### ISSUE TITLE
Export the db/query using Postgres?

### ISSUE THREAD

**Issue by asubbarao** [BurntSushi/nfldb#275]
I've very experienced in SQL, much moreso than Python. It just takes me orders of magnitude longer to query relational databases with Python or whatever other scripting language's engine/API rather than SQL (not to mention SQL is hands down superior when it comes to relational databases). Is it possible to query nfldb only using postgreSQL and not having to deal with the python query class?

**Comment by BurntSushi** [comment]
Yes.
