### ISSUE TITLE
How to install pip on Redhat offline?

### ISSUE THREAD

**Issue by Amruth007** [BurntSushi/nfldb#283]
Hi,

I have tried many ways, but no luck. Can someone please tell me the steps to install pip on Redhat 7 which doesn't have internet connection?

Thanks

**Comment by BurntSushi** [comment]
This isn't the right place to ask general support questions about pip.

If you don't have an Internet connection, then you're going to need to get creative, and it certainly will interfere with your ability to use nfldb.
