### ISSUE TITLE
Ongoing issue with Keyerror

### ISSUE THREAD

**Issue by tzane** [BurntSushi/nfldb#294]
Hi folks,

I am struggling with a key-error exception that is being thrown over gsis_id '2017111911'. There is no such gsis_id in my schedule.json file. This has been happening for a while and I confirmed that there are no records making it into either the Play or Play_Player tables after week 10 of 2017 season. 

```
Traceback (most recent call last):
  File "C:/Python27/Scripts/nfldb-update", line 39, in <module>
    nfldb.update.run(**vars(args))
  File "C:\python27\lib\site-packages\nfldb\update.py", line 535, in run
    doit()
  File "C:\python27\lib\site-packages\nfldb\update.py", line 525, in doit
    update_games(db, batch_size=batch_size)
  File "C:\python27\lib\site-packages\nfldb\update.py", line 397, in update_games
    bulk_insert_game_data(cursor, scheduled, batch_size=batch_size)
  File "C:\python27\lib\site-packages\nfldb\update.py", line 197, in bulk_insert_game_data
    g = game_from_id(cursor, gsis_id)
  File "C:\python27\lib\site-packages\nfldb\update.py", line 54, in game_from_id
    schedule = nflgame.sched.games[gsis_id]
KeyError: '2017111911'
```

The only other mentions I have been able to find on similar key-error exceptions were in two threads [here](https://github.com/BurntSushi/nfldb/issues/264) and [here](https://github.com/BurntSushi/nfldb/issues/196). The solution to the first one was updating schedule.json and players.json in nflgame. The second issue is solved simply by making sure you are running the latest versions of nfldb & nflgame. I've tried running both nflgame update_sched and update_players but still get the same exception after running nfldb-update. Finally, both of my versions appear fully up to date (nflgame==1.2.20 and nfldb==0.2.17).

Hugely appreciate any feedback helping me to trouble-shoot this -- thanks!

**Comment by ochawkeye** [comment]
> There is no such gsis_id in my schedule.json file. 
That is likely the source of your problem.  `2017111911` is the rescheduled week 1 game between TB & MIA.

``` json
   "2017111911",
   {
    "away": "TB",
    "day": 19,
    "eid": "2017111911",
    "gamekey": "57241",
    "home": "MIA",
    "meridiem": "PM",
    "month": 11,
    "season_type": "REG",
    "time": "1:00",
    "wday": "Sun",
    "week": 11,
    "year": 2017
   }
```

You mentioned that you've tried running `nflgame-update-schedule`.  But have you tried to force update  2017?
`python PATH\TO\PYTHON\scripts\nflgame-update-schedule --year 2017`

**Comment by tzane** [comment]
Doh, I forgot you can force a full schedule rebuild for a specific season! All is good now. @ochawkeye to the rescue as usual. Thank you! Closing this issue now.
