### ISSUE TITLE
Updating for 2017 Data

### ISSUE THREAD

**Issue by cminton** [BurntSushi/nfldb#296]
How do I update for 2017 data? I a generating an erro trying to read 2017 data with the nflgame API. I have run pip install --upgrade nflgame. Is there something else I should do? Sorry for the novice question.

**Comment by cminton** [comment]
I ran pip install --upgrade nflgame, so my package is up to date. I am trying to read data for 2017, week 1 and getting an error. The following statement is generating an empty list.

game_list = nflgame.games(year=2017, week=1)

Any thoughts?

**Comment by ochawkeye** [comment]
The version of `nflgame` available on PyPI is quite old and as the library is un-maintained I would not expect it to be refreshed.

You can try pip installing directly from github, which is a more recent version than what is available on PyPI.

```
pip uninstall nflgame
pip install git+https://github.com/BurntSushi/nflgame.git
```
https://github.com/BurntSushi/nflgame/issues/316

**Comment by cminton** [comment]
Thanks ochawkeye. I'll try it tonight.

**Comment by cminton** [comment]
I get the following error:

Collecting git+https://github.com/BurntSushi/nflgame.git
  Cloning https://github.com/BurntSushi/nflgame.git to /private/tmp/pip-aXMmVW-build
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Command "git clone -q https://github.com/BurntSushi/nflgame.git /private/tmp/pip-aXMmVW-build" failed with error code 1 in None

**Comment by cminton** [comment]
Got it to work. I had to reinstall xcode on my mac.
