### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by yahyasheikhnejad** [BurntSushi/nfldb#310]
after installing python properly, setting the environmental variable for system and running the code: python get-pip.py
Result:

Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
ERROR: Could not install packages due to an EnvironmentError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Yahya\\AppData\\Local\\Temp\\pip-req-tracker-rsimtfny\\084f5a8368fb89a7efa9c04f435e93864cabf099a23e186572afd976'
Consider using the `--user` option or check the permissions.

would you please help me to solve it?
I do appreciate your help and support.

**Comment by BurntSushi** [comment]
The first line of the README is: "THIS PROJECT IS UNMAINTAINED."

Your error message has nothing to do with nfldb. The error message even suggests a possible solution to your problem. Maybe you should try it?
