### ISSUE TITLE
ConfigParser with-update 

### ISSUE THREAD

**Issue by jmaslek** [BurntSushi/nfldb#311]
When I run nfldb-update, or pip install --upgrade nfldb, I get the following error:

`Traceback (most recent call last):
  File "//anaconda3/bin/nfldb-update", line 5, in <module>
    import nfldb.update
  File "//anaconda3/lib/python3.7/site-packages/nfldb/__init__.py", line 61, in <module>
    from nfldb.db import __pdoc__ as __db_pdoc__
  File "//anaconda3/lib/python3.7/site-packages/nfldb/db.py", line 2, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'`

I have done both conda install ConfigParser and pip install and the error continues to arise.

**Comment by BurntSushi** [comment]
Before filing issues on a project, please consider reading the README.

Firstly, notice the first line of the readme: https://github.com/BurntSushi/nfldb

Secondly, notice that nfldb requires Python 2.7: https://github.com/BurntSushi/nfldb#installation-and-dependencies
