### ISSUE TITLE
Installed and ran nfldb-update. Data Missing for 2017 and 2018 

### ISSUE THREAD

**Issue by dhruvrajp** [BurntSushi/nfldb#315]
Hi,
I installed and ran nfldb-update. Data Missing for 2017 and 2018 .
Seems like 2017 and 2018 are missing data. 2019 works fine.

**Comment by seanpdwyer7** [comment]
Hi OP,

I’ve found the solution here https://github.com/BurntSushi/nfldb/issues/314

This should help you bulk insert for 2017,2018,&2019.

Best,
SPD

**Comment by dhruvrajp** [comment]
That helped thanks
