### ISSUE TITLE
Python Attribute Error: 'module' object has no attribute 'connect'

### ISSUE THREAD

**Issue by JessePresnell** [BurntSushi/nfldb#76]
Configured the .ini file and attempted to run the python script in the installation guide. When entering code in line by line instead of executing the script I can get through the nfldb.connect() line with no error but nothing is printed. 

```

Traceback (most recent call last):
  File "nfldb.py", line 2, in <module>
    import nfldb
  File "C:\Users\xx\nfldb.py", line 4, in <module>
    db = nfldb.connect()
AttributeError: 'module' object has no attribute 'connect'

```

**Comment by Kirosds** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-170d3e181601> in <module>()
----> 1 ExecuteSQL = sqlalchemy.connect(':memory:')
      2 ExecuteSQL. execute(create_table)
      3 executeSQL.connect()

AttributeError: module 'sqlalchemy' has no attribute 'connect' ??? in jupyter notebook? how to fix or work with SQL???

**Comment by ochawkeye** [comment]
`nfldb` does not use a SQL database.  It is PostgreSQL.  The two are completely different database management systems.  You will not likely get `nfldb` to work with like that.

**Comment by joaoeloy** [comment]
such "basic" error that is actually really hard to comprehend where its comming from... until u do. the amout of time i went on circles to fix this *-* Andrew Gallant BurntSushi@ your wisdom will last for centuries! thanks
