### ISSUE TITLE
Disjunctive query on player position

### ISSUE THREAD

**Issue by elsherbini** [BurntSushi/nfldb#80]
I was trying to query the database for a list of players currently on a team who were either a QB, RB, or WR. 

    db = nfldb.connect()
    q = nfldb.Query(db).player(team__ne='UNK', position=['QB', 'RB', 'WR']).limit(10)
    
    for p in q.as_players():
        print p

This yields a programming error:

    ProgrammingError: operator does not exist: player_pos = text
    LINE 6:             WHERE (((player.position = ANY (ARRAY['QB', 'RB'...
                                             ^
    HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

For reference, this works fine: 

    q = nfldb.Query(db).game(season_type='Regular', team='NE')
    q.game(season_year=[2009, 2010, 2011, 2012, 2013]).limit(5)
    for game in q.as_games():
         print game

    Regular 2009 week 2 on 09/20 at 01:00PM, NE (9) at NYJ (16)
    Regular 2009 week 4 on 10/04 at 01:00PM, BAL (21) at NE (27)
    Regular 2009 week 5 on 10/11 at 04:15PM, NE (17) at DEN (20)
    Regular 2009 week 9 on 11/08 at 01:00PM, MIA (17) at NE (27)
    Regular 2009 week 7 on 10/25 at 01:00PM, NE (35) at TB (7)

Am I thinking about disjunctive queries wrong, or is there something special about player position that makes it not work?

**Comment by BurntSushi** [comment]
Nice find. This is a bug! I've just pushed a fix and updated PyPI to `0.2.10`. If you run `pip install --upgrade nfldb` your code should start working. :-)

**Comment by elsherbini** [comment]
Thanks, that works great. And thanks so much for this amazing project!
