### ISSUE TITLE
Wrong stats in PIT vs CIN game

### ISSUE THREAD

**Issue by DimaKudosh** [BurntSushi/nfldb#89]
Nfldb shows that teams made only 5 first down in game "2014122809"

**Comment by BurntSushi** [comment]
They underlying data from NFL.com is flawed and fixing it is pretty challenging or impossible.

I don't know if that's the case here, but you could check by looking at the GameCenter page for that game on NFL.com and seeing if the data there is correct.

**Comment by DimaKudosh** [comment]
Thank you for your quick reply. Teams in this game made 37 first downs. The problem in play table.
It has records only for first quarter of this game. I try to run nfldb-update, but it doesn't help me.

**Comment by BurntSushi** [comment]
Strange. I might need to investigate further then. In the mean time, could you try deleting the offending game and re-updating? (If you don't delete the game, then `nfldb-update` will consider the game "complete" and will not update it.)

```
[andrew@Liger ~] psql nfldb -c "DELETE FROM game WHERE gsis_id = '2014122809';"
DELETE 1
[andrew@Liger ~] nfldb-update
```

Make sure it says "DELETE 1" after you run the `psql` command.

**Comment by DimaKudosh** [comment]
Thanks, it helped.
