### ISSUE TITLE
utctime type

### ISSUE THREAD

**Issue by rjbks** [BurntSushi/nfldb#92]
I get this error whenever attempting to connect through python (nfldb.connect() or nfldb-update)...
Traceback:

```
---------------------------------------------------------------------------
ProgrammingError                          Traceback (most recent call last)
<ipython-input-3-7437e0ef3f74> in <module>()
----> 1 db = nfldb.connect()

/usr/local/lib/python2.7/site-packages/nfldb/db.pyc in connect(database, user, password, host, port, timezone, config_path)
    135         'Schema has version 0 but is not empty.'
    136     set_timezone(conn, 'UTC')
--> 137     _migrate(conn, api_version)
    138 
    139     if timezone is not None:

/usr/local/lib/python2.7/site-packages/nfldb/db.pyc in _migrate(conn, to)
    445         with Tx(conn) as c:
    446             assert fname in globs, 'Migration function %d not defined.' % v
--> 447             globs[fname](c)
    448             c.execute("UPDATE meta SET version = %s", (v,))
    449 

/usr/local/lib/python2.7/site-packages/nfldb/db.pyc in _migrate_1(c)
    453         CREATE DOMAIN utctime AS timestamp with time zone
    454                           CHECK (EXTRACT(TIMEZONE FROM VALUE) = '0')
--> 455     ''')
    456     c.execute('''
    457         CREATE TABLE meta (

/usr/local/lib/python2.7/site-packages/psycopg2/extras.pyc in execute(self, query, vars)
    221         self.column_mapping = []
    222         self._query_executed = 1
--> 223         return super(RealDictCursor, self).execute(query, vars)
    224 
    225     def callproc(self, procname, vars=None):
ProgrammingError: type "utctime" already exists
```
How can I check for types/domains before attempting to create them? Or is the issue related to something else with migration?

**Comment by ochawkeye** [comment]
Are you setting your `timezone` in `config.ini` to `UTC`?  `UTC` is not technically a timezone, so that might be why there is a problem converting your timezone to UTC.  I'm talking out of my ass here, but if your local time is identical to UTC, I think you could use `GMT` as your timezone name.

`select * from pg_timezone_names ;` should give you the list in its entirety for allowed values for that field in the config file.

**Comment by BurntSushi** [comment]
Are you only running `nfldb.connect()`? If so, it shouldn't be trying to re-create the schema. The only way it tries to create that stuff is if the database is empty. Have you done anything to your database, like changed the table names or adjust the data in any way?

**Comment by rjbks** [comment]
It doesn't seem like the config.ini was the issue, but just in case I checked and US/Eastern seems to be valid

**Comment by rjbks** [comment]
yes only nfldb.connect()
I was wondering why it was recreating all that. The db was reconstructed from the zip file successfully. I am rebuilding it now just to be certain

**Comment by BurntSushi** [comment]
Strange. Basically, when you run `nfldb.connect()`, it inspects the database for its schema version. It compares that schema version with the API version (which is at `7` currently). It then calls `_migrate_N` for each `N` such that `N > {schema_version}` and `N <= {api_version}`.

That means that if `_migrate_1` is being called, then the `schema_version` was detected to be `0`. This value is `0` if and only if the `version` table does not exist or if it is empty.

Given this procedure, could you look at the database you're connecting to and see if there's anything fishy? In particular, what does `SELECT * FROM meta` return?

**Comment by rjbks** [comment]
It seems to be working now.
Not sure what I did that triggered the migration functions. Sorry for the hassle.
