### ISSUE TITLE
Use player_search on specific players?

### ISSUE THREAD

**Issue by cm1291** [BurntSushi/nfldb#93]
Hi everyone...I just want to say that I appreciate all the hard work put in to this project and I can't wait to fully utilize this for my league!

This is definitely a rookie question and I apologize if I shouldn't be asking this here, but I'm trying to write a script where I can take a text file of players and grab their stats for any given week. I currently have a list created:

```
with open("C:\python27\playernames.txt", "r") as inputfile:
    playerlist = inputfile.readlines()
```

Once I have this, I specify which week I'd like to pull stats:

```
theweek = q.game(season_year=2014, season_type='Regular', week=2).as_aggregate()
```

And from here is where I'm having trouble connecting the two. I'd like to cycle through `theweek`, but I'm not sure how to specify that I only want to print the results of those players that are in my `playerlist` (stats included). Would the player_search function help at all with this? I'm at a loss for ideas right now.

Any help that you could give would be great...thanks again for this awesome application!

**Comment by ochawkeye** [comment]
One of the beauties of `nfldb`'s query is that you can keep stringing together more and more detailed info to drill down the specifics of what you're looking for.

For example, your line `q.game(season_year=2014, season_type='Regular', week=2).as_aggregate()` could have been assembled over multiple steps

```python
db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2014)
q.game(season_type='Regular')
q.game(week=2)
print q.as_plays()[0]
```
This would print the "first" play in week 2 of 2014
```(BAL, OWN 35, Q1) J.Tucker kicks 65 yards from BAL 35 to end zone, Touchback.```

Similarly, you can tag on additional query filters.
```
q = nfldb.Query(db)
q.game(season_year=2014, season_type='Regular', week=2)
q.player(full_name="Calvin Johnson")
print q.as_aggregate()[0]
```
```{'receiving_yac_yds': 13L, 'receiving_yds': 83L, 'receiving_tar': 13L, 'receiving_rec': 6L}```

Now, of importance is what the player names in your `playerlist` look like.
If they are nice, pretty, full names, then the example above is pretty close.
```python
playerlist = ['Calvin Johnson', 'Tom Brady']
for player in playerlist:
	q = nfldb.Query(db).game(season_year=2014, season_type='Regular', week=2)
	q.player(full_name=player)
	print player
	print q.as_aggregate()[0]
```
```
Calvin Johnson
{'receiving_yac_yds': 13L, 'receiving_yds': 83L, 'receiving_tar': 13L, 'receiving_rec': 6L}
Tom Brady
{'passing_incmp_air_yds': 88L, 'passing_sk': 1L, 'passing_att': 22L, 'passing_sk_yds': -7L, 'passing_yds': 149L, 'passing_incmp': 7L, 'passing_cmp': 15L, 'rushing_att': 1L, 'passing_tds': 1L, 'passing_cmp_air_yds': 83L}
```

If the names, are in a format similar to what would be used by NFL.com & `nflgame`, you might try something like this:

```python
playerlist = ['C.Johnson, DET', 'T.Brady, NE']
for player in playerlist:
	gsis_name, team = player.split(', ')

	q = nfldb.Query(db).game(season_year=2014, season_type='Regular', week=2)
	q.player(gsis_name=gsis_name, team=team)
	print player
	print q.as_aggregate()[0]
```
```
C.Johnson, DET
{'receiving_yac_yds': 13L, 'receiving_yds': 83L, 'receiving_tar': 13L, 'receiving_rec': 6L}
T.Brady, NE
{'passing_incmp_air_yds': 88L, 'passing_sk': 1L, 'passing_att': 22L, 'passing_sk_yds': -7L, 'passing_yds': 149L, 'passing_incmp': 7L, 'passing_cmp': 15L, 'rushing_att': 1L, 'passing_tds': 1L, 'passing_cmp_air_yds': 83L}
```

Finally, and this is one still impresses me (:clap: @BurntSushi ), if the data came from some careless data entry outsourced to a non-NFL fan.
```python
playerlist = ['Calvis Johnson', 'Tammy Brady']
for player in playerlist:
	nfldb_player = nfldb.player_search(db, player)[0]

	q = nfldb.Query(db).game(season_year=2014, season_type='Regular', week=2)
	q.player(player_id=nfldb_player.player_id)
	print player, '>', nfldb_player.full_name
	print q.as_aggregate()[0]
```
```
Calvis Johnson > Calvin Johnson
{'receiving_yac_yds': 13L, 'receiving_yds': 83L, 'receiving_tar': 13L, 'receiving_rec': 6L}
Tammy Brady > Tom Brady
{'passing_incmp_air_yds': 88L, 'passing_sk': 1L, 'passing_att': 22L, 'passing_sk_yds': -7L, 'passing_yds': 149L, 'passing_incmp': 7L, 'passing_cmp': 15L, 'rushing_att': 1L, 'passing_tds': 1L, 'passing_cmp_air_yds': 83L}
```

**Comment by cm1291** [comment]
This is awesome! I think I was getting lost in figuring out how to use `as_aggregate()`, but your examples are working like a charm. Thanks for taking the the time to help out a rookie...this application is fantastic!
