### ISSUE TITLE
drive table possession times

### ISSUE THREAD

**Issue by KateDavis** [BurntSushi/nfldb#94]
Can you please help with the drive table? I have multiple records that overlap Q1/Q2 or Q3/Q4, so although possession times per half add up properly, the quarters don't.

Is this an inconsistency within the gamecenter JSON? A load error? 

I am trying to compute percent possession time per quarter, and it's a bit dodgy right now.

**Comment by BurntSushi** [comment]
Could you help me to understand your problem? The best way to help me understand is to provide some small amount of code that doesn't do what you expect. What have you tried? What is it doing? What do you think it should be doing?

Note that [`Drive`](http://pdoc.burntsushi.net/nfldb#nfldb.Drive) objects have a `pos_time` field, which has type [`PossessionTime`](http://pdoc.burntsushi.net/nfldb#nfldb.PossessionTime). A `PossessionTime` has a `total_seconds` field which should be useful for adding times up.

**Comment by KateDavis** [comment]
Drive can span quarters. I wanted to calculate a possession time percent by
quarter, so I went down to the play level. This is part of the gamecenter
data structure, but it's something that should be documented.

**Comment by BurntSushi** [comment]
Well, it's not just "part of the GameCenter data structure." The possession time of a drive, *by definition*, can span quarters. I don't really see any reason to expect otherwise.

Using play data is probably the right heuristic for possession time by quarter.
