### ISSUE TITLE
nfldb not returning previous year's team roster

### ISSUE THREAD

**Issue by ForTozs** [BurntSushi/nfldb#95]
I am trying to calculate team sacks on a per game basis. So far I have only been able to list all players for a particular game, which would be fine, except the team data is not correct. Here is some example code:

```
q = nfldb.Query(db)
q.game(season_year=2014, season_type='Regular', week=17, team='NO')
players = q.as_players()
index = []
for i in range(0, len(players)):
    index.append(players[i].player_id)

for j in range(0, len(players)):
    player_stats = nfldb.aggregate(q.as_play_players())[j]
    print player_stats.player.full_name, player_stats.player.team
```

The output of this not only includes NO players, TB players, and 'UNK', but also players from MIA, SEA, etc. Is this a bug in the database, or does nfldb not have the ability to determine pervious years' rosters?

**Comment by BurntSushi** [comment]
Player meta data is always a reflection of the current state of the world.

Each statistic, however, is recorded with the team. You just need to access that instead:

```python
    print player_stats.player.full_name, player_stats.team
```

This replaces `player_stats.player.team` with `player_stats.team`.

**Comment by ForTozs** [comment]
Great. Thanks!
