### ISSUE TITLE
nfldb stats

### ISSUE THREAD

**Issue by vinnypimp** [BurntSushi/nfldb#96]
I noticed there aren't any stats for the 2015 preseason, but there were preseason stats last year. Is there a bug? The game table shows the correct 2015 schedule but the scores are 0-0.

**Comment by BurntSushi** [comment]
Have you run nfldb-update?

**Comment by vinnypimp** [comment]
I did. The schedule updated and showed the games as final with 0-0 scores. Also, there were no player stats. I also ran a python script to see if it was my import and it too game back with no stats.

**Comment by vinnypimp** [comment]
Was thinking.. I haven't made any updates to the modules. Can that be the reason? It was working fine last season. Were there any updates made between end of last season and now?

**Comment by BurntSushi** [comment]
You should always be upgrading. If something isn't working as expected, the very first thing you should try is upgrading. To make sure you have the latest, run `pip install --upgrade nfldb`. Then run `nfldb-update` again.
