### ISSUE TITLE
Display current game clock time for in progress games

### ISSUE THREAD

**Issue by jeffmoreland** [BurntSushi/nfldb#97]
What is the best way to show/print the current game clock for games that are in progress?

**Comment by BurntSushi** [comment]
I'd probably the `time` of the last play: `game.drives[-1].plays[-1].time`.

**Comment by BurntSushi** [comment]
Or even shorter, `game.plays[-1].time`.

**Comment by jeffmoreland** [comment]
That's it! Thanks.
