### ISSUE TITLE
Incorrect turnovers for PIT @ NE

### ISSUE THREAD

**Issue by mazubieta** [BurntSushi/nfldb#98]
I just did an update and noticed that it's showing 2 turnovers for the Patriots and 0 for the Steelers.  I believe this is incorrect and should be just 1 for Steelers.

http://espn.go.com/nfl/matchup?gameId=400791485

**Comment by ochawkeye** [comment]
What query are you running that shows that PIT had 2 turnovers?

```python
import nfldb

db = nfldb.connect()
q = nfldb.Query(db)
q.game(season_year=2015, season_type='Regular', week=1, finished=True)
for game in q.as_games():
    print game

turnovers = nfldb.QueryOR(db).play(defense_int__ge=1, defense_frec__ge=1)
q.andalso(turnovers)
for play in q.as_plays():
	print play
```

```
Regular 2015 week 1 on 09/10 at 07:30PM, PIT (21) at NE (28)
(PIT, OPP 46, Q4, 1 and 10) (7:09) (No Huddle, Shotgun) B.Roethlisberger pass deep left intended for D.Heyward-Bey INTERCEPTED by D.Harmon at NE 7. D.Harmon ran ob at NE 7 for no gain.
```

**Comment by ochawkeye** [comment]
Oh...

```python
for game in q.as_games():
    print game
    print game.home_team, game.home_turnovers
    print game.away_team, game.away_turnovers
```
```
Regular 2015 week 1 on 09/10 at 07:30PM, PIT (21) at NE (28)
NE 2
PIT 0
```

**Comment by BurntSushi** [comment]
Not our problem unfortunately. It's reported incorrectly upstream: http://www.nfl.com/liveupdate/game-center/2015091000/2015091000_gtd.json

@ochawkeye's solution is probably what you should use instead. Although it is possible for play-by-play data to be off too. Here's some similar code but factored out into a function (and also so you can find it per team):

```python
import nfldb


def turnover_plays_for_team_in_game(db, team, gsis_id):
    q = nfldb.Query(db)
    q.game(gsis_id=gsis_id)
    q.play(pos_team=team)
    q.andalso(nfldb.QueryOR(db).play(passing_int=1, fumbles_lost=1))
    return q.as_plays()


if __name__ == '__main__':
    db = nfldb.connect()

    gsis_id = '2015091000'
    ne_turnovers = turnover_plays_for_team_in_game(db, 'NE', gsis_id)
    for play in ne_turnovers:
        print play
    print 'NE turnover count', len(ne_turnovers)

    print '-' * 79

    pit_turnovers = turnover_plays_for_team_in_game(db, 'PIT', gsis_id)
    for play in pit_turnovers:
        print play
    print 'PIT turnover count', len(pit_turnovers)
```

**Comment by mazubieta** [comment]
Thanks for looking into it.  In cases like this, do you typically see these
fixed eventually? If so does that make it into a future update? Or do I
need to maintain my own Stat corrections?

I've only recently started using this db for custom fantasy league, so I
guess I'm wondering what kind of additional maintenance I'll need to do as
the season progresses.

Thanks, again.

**Comment by BurntSushi** [comment]
@mazubieta The source data is not always accurate and there are not always updates. We do not maintain stat corrections. If you search the `nflgame` or `nfldb` issue tracker, you'll find loads and loads of previous issues on this problem. But the TL;DR is: if you need 100% accurate stats, you're going to need to do some kind of manual curation and it isn't going to be easy.

**Comment by mazubieta** [comment]
Sounds good. Thanks, Andrew.
